### PR TITLE
LPS-74412 SF

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:stop

**Comment by robertoDiaz** [comment]
@sergiogonzalez 

Any update on this??

Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51497. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
