### PR TITLE
LPS-63481 Remove unnecessary test

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @sergiogonzalez, hope you're good :)

This is part of one task we're working to remove the static calls from our modules. This pull is a requirement for other subsequent tasks.

Could you please double check?

cc @inacionery 

Thanks a lot!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @marcellustavares 

Thanks for sending this :)

The pull looks totally ok to me :+1:  so I don't have any concern with the code. The only thing that I might think of is that we should let @mdelapenya know about this since it seems that one test he wrote is being removed so maybe it's interesting to find an alternative and probably @mdelapenya knows best.

Thanks guys!

**Comment by mdelapenya** [comment]
Hi guys, the test here is testing that any component providing the `DLDisplayContextFactory` service, which is located in portal-service, is registered. So the real purpose of this test is to verify that the extension point is working as expected.

The test should be updated to add a _test_ implementation of that interface instead of a real one, as it was doing by extending `BaseDLDisplayContextFactory`, so that any client code providing an implementation of the `DLDisplayContextFactory` service knows that will be tracked and added to the DisplayContext system.

If you have any doubt, please ask us about it.

Thanks!

**Comment by marcellustavares** [comment]
hey @mdelapenya, are `DLDisplayContext` implementation being injected by OSGi?

**Comment by marcellustavares** [comment]
thx for reviewing @sergiogonzalez!

**Comment by mdelapenya** [comment]
Yes, please take a look here: https://github.com/liferay/liferay-portal/blob/453855d6eb159d6aebf1eacd45c83d65d4cab3c9/portal-service/src/com/liferay/portal/kernel/display/context/BaseDisplayContextProvider.java#L100

It has a ServiceTrackerCustomizer listening for new implementations.

**Comment by marcellustavares** [comment]
got it, we'll update to service reference and remove the test. Does it sound ok?

**Comment by mdelapenya** [comment]
But we need a test for the extension point too.

**Comment by marcellustavares** [comment]
Ok, will send you a pull request soon :) Thx @mdelapenya

**Comment by mdelapenya** [comment]
Great! Thank you team :smiley:

**Pull request closed without merging**
