### PR TITLE
[TECHNICAL-SUPPORT] LPS-70514

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@sergiogonzalez Might be good to pass this through @marcellustavares too since it changes DDM. Thanks!

**Comment by jonathanmccann** [comment]
I'll work on these test failures.

**Comment by mbowerman** [comment]
@jonathanmccann @marcellustavares Oh! There's a structure.getClassNameId() method. Likely, we should use that [here](https://github.com/sergiogonzalez/liferay-portal/pull/3784/commits/9fb137e2c3f245b5f3c7bd43b946844ae8d0514d#diff-141f0ef0c60e2b0e65a7ff661e8dc6e0R502) instead of hard-coding in the class name for JournalArticle. Also, we may need to do some similar logic [here](https://github.com/sergiogonzalez/liferay-portal/pull/3784/commits/d2239a9d3049ff23a91a47ec076349818b6c72e7#diff-4ddff4ea11010e4108d7f2c066dd3dbdR219) (going from DLFileEntryType > DDMStructureLink > DDMStructure > classNameId), rather than always using DLFileEntry.class.getName().

**Comment by jonathanmccann** [comment]
@mbowerman Go ahead and make those changes and resend it to me. I'll try to figure out what's going on with the tests I added.

**Comment by mbowerman** [comment]
Hi @jonathanmccann,

Please see https://github.com/jonathanmccann/liferay-portal/pull/1217. I did not make the changes I proposed to DLFileEntryTypeLocalServiceImpl because the settings_ field stores it with the classNameId for DLFileEntry, whereas the structureId stores it with the classNameId for DLFileEntryMetadata.

**Pull request closed without merging**
