### PR TITLE
[TECHNICAL-SUPPORT] LPS-73857

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @ChrisKian 
Can you please explain a little bit more why this is needed? According to the commit it seems that the issue is because "DBStore stores the thumbnails without the version number in the directory". It seems that DLPreviewableProcessor only deals with DLStore and that should abstract of the actual store implementation. Then, I don't think that we need to do any change in DLPreviewableProcessor, maybe we need to change and fix DBStore?
Thanks

**Comment by ChrisKian** [comment]
Hey @sergiogonzalez,
The reason this fix is needed is due to the way DBStore stores the DLContent.  For example, when saving a content using FileSystemStore, the content is saved with the file path "/path/to/filename.jpeg/versionNum".  When using DLStoreUtil.deleteDirectory(), we are trying to delete any content which matches the path "/path/to/filename.jpeg/*".
However, when using DBStore, we store the path information differently.  In the DLContent table, the path column would be something like "/path/to/filename.jpeg" and a separate version column would contain the version number.  So, when trying to remove "/path/to/filename.jpeg/*", we return no matches since the path is treated as a specific file rather than directory.

I specifically chose to place DLStoreUtil.deleteFile() in DLContent in case any other store implementations also treat their file paths the same.  Also, I would be modifying the DBStore.deleteDirectory() method to only remove a specific file when there is already a deleteFile() method.  On top of that, the DBStore.deleteDirectory() method goes into DLContentLocalService.deleteContentsByDirectory(), which forces a directory to be removed.
Adding the deleteFile() method is safe; no errors are thrown if it cannot file the file.  I would have done a check for the content first, but since it's safe to try to remove content which isn't there, I figured the extra check wouldn't be needed.

Please let me know what you think or if there is anything else I can help answer.  Thanks!

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/50675. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Thanks for the explanation @ChrisKian I have fwded the pull to Brian

**Pull request closed without merging**
