### PR TITLE
LPS-66188 Upon searching the children pages to be deleted, only find …

### PR DESCRIPTION
**Pull request by dsanz**
…the latest version

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
I talked to @dsanz and it seems that the bug could be in a different place https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-service/src/main/java/com/liferay/wiki/service/impl/WikiPageLocalServiceImpl.java#L503

We should create a bunch of integration test in WikiPageLocalServiceTest to ensure that this feature works as expected.

**Comment by dsanz** [comment]
Hi @hudakl , I got some feedback from @sergiogonzalez. Could you please open a question in Collab&DM SME forum? We'll better discuss this there.

Best

**Comment by hudakl** [comment]
Hi Daniel and Sergio,

Thank you for your reply. I'll perform tests with the changeParent method, and based on the results I'll post the forum thread.
However, due to my current tasks I could only get to it on Monday.

Would that be OK for you?

Thank you,
Laci

**Comment by dsanz** [comment]
It's ok for me @hudakl. The changes suggested by @sergiogonzalez are about moving a page from a parent to another. Seems there is a bug there because we just move the last version. If we move all versions so that all of them share parent page, then deletion of parent page would work ok.

Please try this and let us know.

Thanks!

**Comment by hudakl** [comment]
Hi,

Sorry for my late reply.
I've checked Sergio's suggestion about the changeParent(...) method, however, I believe it is the intended operation to change only the last version's parent, because on the History we can revert this change too. If we change the parent of all versions, we can not revert to the previous parent version.
Do you agree with this?
If yes, is my original solution acceptable?
If not, what could be the proper solution?

Thank you,
Laci

**Comment by dsanz** [comment]
cc @sergiogonzalez

**Comment by sergiogonzalez** [comment]
Hey @hudakl @dsanz 

Sorry for the delay in the reply, I was on vacation last week.

When we change the parent of a page we want to change it in all the versions of that page. For simplicity we want every version of the page to have the same parent. 

If we don't have this we would have a more complex logic. What would happen if you are reverting to a page version that has a parent page that has been deleted?

Let's keep it simple for now and assume that all versions of a wiki page should have the same parent.

**Comment by hudakl** [comment]
Hi Sergio,

Thank you for your reply. Unfortunately I didn't have time yet to come up with the new solution in detail and my first plan did not work.
I can send you the new pull in about a week as I'll be on holiday next week. I'll let you know of my results.

Thank you,
Laci

**Pull request closed without merging**
