### PR TITLE
LPS-76038 When the user is trying to view a pending DLFileEntry, the owner should be allowed

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @yuhai
Isn't this bug reproducible for other entries/content such as JournalArticle or BlogEntry?
It looks to me as something generic, but the logic in those places is different to this fix.

**Comment by yuhai** [comment]
Hi @sergiogonzalez 

The issue can't be reproduced in JournalArticle or BlogEntry. 

They have different display behavior.
For blog, the user can see other user created pending blog. 
For journalarticle, the owner can't see own created journalarticle.

The main difference is that DLfileentry existed the logic (LPS-72547 added it) (a071271500884c8a8d6b128a7bc508e03a4e971a) and (27a4eaeadbc10dd0e179a68b39aab803fe6e65b2). For the issue, when check view permission for the latest version, it will return false (https://github.com/liferay/liferay-portal/blob/f8b99719ab52c608ee52352658abff4878f0f531/portal-impl/src/com/liferay/portlet/documentlibrary/service/permission/DLFileEntryPermission.java#L137) so that the issue happened. For LPS-72547 issue,  JournalArticle or BlogEntry didn't have the issue.

Regards,
Hai

**Comment by adolfopa** [comment]
Hey @yuhai @ealonso 
This change gives file entry owners too much power. There are two problematic cases:
1. A user creates a document (so he is the owner) and there is a workflow in place. With your changes, this user will be able to modify the file entry in the middle of the review process, making the workflow itself pointless, as there's no way to control the changes made by the original users.
2. If the site is staged, no matter what the value of the STAGING_LIVE_GROUP_LOCKING_ENABLED property is, the owner of a document will be able to do anything with it.
I think a possible fix would be to let the owner view the file entry (but only view it) around line https://github.com/liferay/liferay-portal/blob/f8b99719ab52c608ee52352658abff4878f0f531/portal-impl/src/com/liferay/portlet/documentlibrary/service/permission/DLFileEntryPermission.java#L137.

**Comment by sergiogonzalez** [comment]
Hey @yuhai 
I'm closing this pull. Please send any changes to @adolfopa instead.
Thanks!

**Comment by adolfopa** [comment]
See https://github.com/sergiogonzalez/liferay-portal/pull/4138

**Pull request closed without merging**
