### PR TITLE
LPS-63635 Inline JSP fragment

### PR DESCRIPTION
**Pull request by adolfopa**
@sergiogonzalez This is the first in a series of pull requests for the SO Activities portlet.

This PR imports the plugin as an OSGi module and does some cleanup in preparation for the upcoming pull request.

The idea is to replace the current Activities portlet with this one, as it offers a superset of the funcionality of the portal one. Once I finish importing the new one, I'll move it into social/social-activities-web and delete the old one.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/228. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
