### PR TITLE
LPS-68797

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Sergio,
We tested it and it works well.

Thanks,
Dale

**Comment by sergiogonzalez** [comment]
ci:reopen ci:retest

**Comment by sergiogonzalez** [comment]
ci:reopen ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44358. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/3bbd7be~3...3bbd7be) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
