### PR TITLE
LPS-66016 Same fix for other upgrades

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @jorgeferrer

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40257. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
