### PR TITLE
LPS-83963 Small Image not available while editing blog entry after upgrade to DXP

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz 

I implemented the first 3 points of your suggestions in https://github.com/robertoDiaz/liferay-portal/pull/714#issuecomment-412831666 (as separate commits).

I'm not sure however, that 4 (using the API of Blogs local service) could be applied here.
addAttachmentFileEntry would add an attachment to the Blogs entry, not a small image. The latter is not implemented as an attachment of a Blogs entry.
Turning public and using addSmallImageFileEntry would not work because the method expects an ImageSelector, which has to be properly initialized. Adding small images are done by employing the Image Selector, but in our case, in the upgrade process, we cannot use that.

When designing the upgrade process I took multiple APIs into consideration, but found that only PortletFileRepositoryUtil has an API where all the the data that is available in the upgrade environment can be passed to it's method.
Also PortletFileRepositoryUtil is used by addSmallImageFileEntry.

Please let me know what you think.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @robertoDiaz @istvanD 
We didn't write any upgrade for the small images because we wanted that process to be lazy, so whenever a user updates a blog entry the small image would be converted to a FileEntry. We still want it to be that way at least for now, so I'm not merging this pull request.
Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

That you for the analysis.
Are there any plans (LPSes) to implement the lazy loading.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hey @robertoDiaz @sergiogonzalez 

I see that `BlogsEntryImageSelectorHelper` is a class that deals with Blog Images.
In `getImageSelector()` one if clause checks for `_oldSmallImageId`, which is an ID of a legacy image before an upgrade (not in DM, but in the image DB table).
https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/util/BlogsEntryImageSelectorHelper.java#L44

If the user uploaded a new image, `PortletFileRepositoryUtil` will return that fileEntry, and set the `ImageSelector` with it.

However, if no file was uploaded during editing, an "empty" `ImageSelector` will be returned.

Isn't that part were the lazy-loading is supposed to be implemented? If there is no new image uploaded `(imageFileEntryId == 0)` but a legacy image is there `(_oldSmallImageId != 0)` then there should a new `fileEntry` be created on the fly, and set `ImageSelector` to deal with the file, so that when the blog update finishes, that new `fileEntry` will become the Blog's new small image.

Can we go with this approach?

Thank you and best regards,
István

**Comment by sergiogonzalez** [comment]
Hey @IstvanD yeah, that's the way it should behave AFAIK. 
@adolfopa can you confirm it?
Thanks!

**Comment by adolfopa** [comment]
The implemented behaviour is a bit different that what you expect. What we have is not a lazy upgrade, but a "safe replacement" strategy.

We don't really migrate (legacy) small images, but we make sure that when a user deletes a legacy image from a blogs entry, or replaces it with a new FileEntry, the legacy image is properly deleted.

This is handled in BlogsEntryLocalService#updateEntry (look for usages of the `deletePreviousSmallImageId` variable).

**Comment by IstvanD** [comment]
Hey @adolfopa 

Thank you for the explanation.
It is the expected behavior for the legacy image to be visible in the Blog Entry after an 6.2 => DXP upgrade? Currently, this is not the case.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hello @adolfopa, @sergiogonzalez 

Could you please take a look at my last question?

Thank you and best regards,
István

**Comment by sergiogonzalez** [comment]
Hey @IstvanD since the current behaviour is a little different than what I expected (it's not really a migration what we are doing) we are reconsidering this pull request to be merged. We'll keep you posted.

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/702. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Many thanks for letting me know.
I'm looking forward to the results.

**Pull request closed without merging**
