### PR TITLE
[Waiting to determine the reviewer] LPS-52188

### PR DESCRIPTION
**Pull request by samuelkong**
cc @arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:reopen

**Comment by samuelkong** [comment]
Test failure not related

**Comment by sergiogonzalez** [comment]
I'm sending this pull to Scott Lee because he owns the Mail portlet. Thanks @samuelkong

**Comment by sergiogonzalez** [comment]
Hey @samuelkong I'm closing this pull per email conversation. 
Thanks!

**Pull request closed without merging**
