### PR TITLE
LPS-61983 Remove leftover tag reference and fix styles

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/190. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
