### PR TITLE
[TECHNICAL-SUPPORT] LPS-80609

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @sergiogonzalez, this is an updated fix applying the pattern you set here: https://github.com/SamZiemer/liferay-portal/pull/442. Let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by sergiogonzalez** [comment]
Hey @SamZiemer there seems to be a real failure in the tests?
Can you please take a look and resend?
Thanks!

**Comment by SamZiemer** [comment]
I'll take a look.

**Comment by SamZiemer** [comment]
I've sent a new fix here: https://github.com/sergiogonzalez/liferay-portal/pull/4451

**Pull request closed without merging**
