### PR TITLE
[TECHNICAL-SUPPORT] LPS-69226

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Alec-Shay

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey guys,

Is this changed required after the changes done in https://github.com/brianchandotcom/liferay-portal/pull/44814 ?
I think that with those changes we shouldn't need this?

Thanks!

**Comment by Alec-Shay** [comment]
Hi @sergiogonzalez,

You're right, it looks like those changes affect the control flow so that this code isn't reached anymore, so that indirectly fixes this issue.

Do you think we should just leave this alone then? I still feel like, if somehow we still ended up using this file with a "/message_boards/view_my_posts" MVCRenderCommand, we'd run into this bug again. And if there is no such case, then do we need this code here at all?

Just feel like it's worth asking. In any case though, I'll wait for brianchandotcom#44814 for the fix for the client. Thanks for looking at this.

**Comment by Alec-Shay** [comment]
@sergiogonzalez To be clear, we've delivered a patch for the client for the other issue, but want to also fix the underlying issue in place here in case any future code changes (or even custom code) end up executing this code and re-discovering this bug, before we resolve the remaining tickets.

Does a fix like this seem appropriate to you, for the code currently in place?

**Comment by Alec-Shay** [comment]
Hello @sergiogonzalez,

Can we re-open this pull, unless there's a reason not to? Or should I send a new pull instead?

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay It shouldn't be mandatory to provide a status attribute to the taglib because it should automatically infer it from the model context. So we can leave it as it is. 
You can see the same use case here https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-web/src/main/resources/META-INF/resources/blogs_admin/entry_search_columns.jspf#L136

**Comment by Alec-Shay** [comment]
@sergiogonzalez https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/ui/SearchContainerColumnStatusTag.java#L55 at this location, for the message_boards/view.jsp example, `resultRow.getObject()` only returns an `AssetEntryImpl` (which does not have a status field), whereas the blogs example returns the more specific object, so it works for that case.

I think the problem is that the wrong className is being passed in for the search container, so it will not be cast to an MBThread, rather than a generic object, for which it can't get the status directly.

However, while for the Blogs example, the Blogs className can be specified to allow it to work (on this line: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-web/src/main/resources/META-INF/resources/blogs_admin/view_entries.jsp#L208), `BaseModel` is used for the message boards threads (right here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view_threads.jspf#L67).

If I try to use MBThread as the className though, then it will throw an error, because the search container cannot cast the model to an AssetEntry (or at least, that was the result in my testing).

As such, I think the only way for the status field to be usable for this search container is to explicitly set the value. If we do not change this, then the status field where it is is unusable, and prone to NullPointerException errors.

**Comment by Alec-Shay** [comment]
@sergiogonzalez  Does this explanation make sense? Perhaps the search container className should be using `MBThread`, but the fact that that doesn't work is a bug on its own?

My current assumption is that `MBThread` is not applicable to be treated as an AssetEntry the same way as `BlogsEntry` is, so it cannot infer the status and that value needs to be passed in explicitly. If I'm wrong though, then I guess something needs to change for the search container so it can handle the `MBThread` class, for this code to be stable. I'm not sure exactly what that would be, though.

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay yeah, that make sense. Can you please send me a pull with those changes?
Thanks!

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay yeah, that make sense. Can you please send me a pull with those changes?
Thanks!

**Comment by Alec-Shay** [comment]
@sergiogonzalez Sorry for the delayed response. Just to be clear, what kind of changes do you mean?

**Comment by Alec-Shay** [comment]
@sergiogonzalez Here is the problem I get trying to implement a change to the search container (if I assume that's what you meant):

At this location in `view_threads.jspf`, the search container is defined to use the `BaseModel` class, which causes a problem when this use case needs a result as an `MBThread` to detect the `status` field: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view_threads.jspf#L67

However, all the other code we have in place expects the result from this search container to be an `AssetEntry`, so just getting rid of `BaseModel` causes even worse problems for the MB portlet (the portlet becomes unresponsive because we are using an `AssetEntryQuery` in `view_threads.jspf`).

That said, I am not able to use the same search container row to handle multiple potential classNames.

If you try to determine the className to use along with `search-container-row` tag like so...

```
<liferay-ui:search-container-row
	className= "<%= searchContainerClassName %>"
	keyProperty="primaryKeyObj"
	modelVar="result"
>
```
... then the search container won't actually be able to pick it up. It apparently needs an explicit definition, and the jsp won't resolve it for the liferay-ui tag here.

But if you try to do an approach without setting the value within the `search-container-row` tag...
```
<liferay-ui:search-container-row
	keyProperty="primaryKeyObj"
	modelVar="result"
>
	<%
	searchContainer.setClassName(searchContainerClassName);
	%>

	// ...

</liferay-ui:search-container-row>
```
... then you get this error: "PWC6130: According to the TLD or the tag file, attribute className is mandatory for tag search-container-row". This indicates that `className` must be defined at this specific point, and apparently must use only a single, particular className. If it can't cast from `AssetEntry` to `MBThread`, then it seems like the same search container cannot be used for both.

So, the only other way I can think to implement this would be to make a totally separate search container just for this case, which I feel would unnecessarily make things significantly more complicated, and possibly reduce maintainability code-wise.

To me, this also seems to be why all the other displayed fields in `user_thread_columns.jspf` explicitly set their respective values (as you can see: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/user_thread_columns.jspf). This is why I still don't quite understand why the status field's value in particular must be retrieved from the model implicitly.

Perhaps I'm missing something though and there is another approach, but if so, then I'm not sure exactly what is expected. Maybe I'm misunderstanding something about how to use the search container? What should be the proper way to go about this?

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay thanks for the detailed explanation, I think we can go ahead with the changes you proposed, I'll reopen the pull and send to Brian.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45271. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
Thanks, Sergio!

**Pull request closed without merging**
