### PR TITLE
LPS-68552

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @sergiogonzalez,

This bug and fix is a little strange, but we're trying to stay within the confines of how the portlet was set up. Basically, we do not keep track of the "start" or how many activities there are in total. Due to that, we need to do some interesting logic in order to calculate the pagination. Here is a more detailed description from @samziemer:

> Currently, when we have more activities to list than whatever the display max is set to in the configurations of the social activities portlet, we do not see the "see more" button and the number of activities displayed is double whatever is set in the configuration.
> 
> This commit fixes that issue, however it leaves one potential issue. The see more button is shown when the number of activities in a set equal the max to be shown.
> 
> For example, if you have 6 activities and configure the portlet to show only 2 at a time, you can click on the see more button until you have paged through all activities. However, the button is still shown. Clicking one more time leads to a page that displays "no more activities to load at this time"
> 
> I am not sure if the current pagination was intended or not. We don't have any way to track the total number of activities that can be shown so checking the total number available is not possible at this time.

Let me know what you think.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:reopen

**Comment by SamZiemer** [comment]
hi @sergiogonzalez, I wanted to see if you have had a chance to look at this issue yet?

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/351. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @SamZiemer I have forwared the pull to @adolfopa because I think that this fix can create some issues, and Adolfo has more knowledge about this portlet so he can do a better review.
Thx!

**Pull request closed without merging**
