### PR TITLE
LPS-76038 Let owner view his pending entries

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by yuhai** [comment]
Thanks, @adolfopa 

Regards,
Hai

**Comment by yuhai** [comment]
Hi @sergiogonzalez 

Since the issue came from EE customer, do you have a chance to review this?

Regards,
Hai

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53375. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
