### PR TITLE
LPS-59105

### PR DESCRIPTION
**Pull request by topolik**
Hi Sergio,

there are Poshi errors, but I don't understand what's wrong there.

I tried to manually go through one of the Poshi test (add DDL template) and I was able to finish it. I'm not sure what that "warnings" means?

Can you please help me?

Thank you.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @topolik I let @sharonchoi know about this and somebody from WCM qa engineers will check this.
I don't get why the tests can be failing either...

**Comment by topolik** [comment]
Thank you very much Sergio!

-- tom +

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
I'll close this pull since @robertoDiaz is taking care of this.

**Pull request closed without merging**
