### PR TITLE
LPS-68589 Since kernel 2.4 it is needed to introduce javax.portlet as dependency

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by zxdgoal** [comment]
Bump

**Comment by daledotshan** [comment]
Hey Sergio,
Could you help to review this fix? it is for a ee customer
Thanks,
Dale

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/490. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/74bb7c3~6...74bb7c3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
