### PR TITLE
[TECHNICAL-SUPPORT] LPS-62572

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @kayleen-lim:

> This is one possible solution to the issue in https://issues.liferay.com/browse/LPS-62572.
> 
> The main issue is that MBMessageLocalService.getMessageDisplay is using a MBThreadPersistenceImpl.filterFindBy\* method to find previous/next entries, but those methods currently yield incorrect results because there are no resource permissions for MBThread. Instead, we should check for MBMessage resource permissions. So I have created a new finder method to do so.
> 
> I also did not create additional constants because there are a lot of constant strings already in the MBThreadFinderImpl class, although, I am not sure exactly what I should do in this case.
> 
> Another solution I considered was creating resource permissions for MBThread, but that would require additional changes, including some to jsp's.
> 
> Let me know how I can improve or change the solution. Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann 

Regarding this pull the behaviour that is changing here is something that we are considering to remove it because most of the products and solutions for Message Boards and Forums don't offer that kind of navigation for previous and next threads and we are considering removing  that feature for the next release. Do you think this could be an issue?

**Comment by jonathanmccann** [comment]
Hey @sergiogonzalez,

I'm not sure what you mean by "Do you think this could be an issue?". If you think that it's not worthwhile to merge in this fix if you are simply going to remove the feature, then that is fine. We can commit the fix to ee-6.2.x so that the client is taken care of. If I misunderstood, feel free to let me know.

Thanks.

**Comment by sergiogonzalez** [comment]
Yeah, that's one thing. The other thing is that, considering that this customer report an issue about that I'm assuming that they are using this feature, right? Can we get somehow the information about if they are using it and for what? Would it be a big deal for them if we remove this? Just to have more information about if we should drop the support for that feature, because as I commented before, almost every Message Boards product we saw don't have that feature and I don't personally see it as a useful feature but like adding more complexity and noise to the user interface.

**Comment by jonathanmccann** [comment]
Gotcha. I'll have @kayleen-lim follow up with the client to get information about their use case. Thanks Sergio!

**Comment by sergiogonzalez** [comment]
@kayleen-lim commented that the customer wouldn't have any issue with removing those links so I'm planning to remove them from 7, so it doesn't make sense to merge this pull in master. Therefore I'm closing this pull. Thanks @jonathanmccann @kayleen-lim

**Pull request closed without merging**
