### PR TITLE
LPS-53557

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @kayleen-lim @jonathanmccann 

I was checking this issue more carefully and I think that this fix will create even more confusion to the end users. 

When the users searches in Documents and Media they can't apply any filter to the search, which means that it will search based on the folder where it's located, and not based on the document type, mine, recent section, etc.

Actually, when you are in Recent or Mine or you have selected a particular document type, and then you search, the search results maybe documents that are not in Recent, Mine or with that particular document type. Then, the concept of selecting home when the user searches it doesn't seem like a bad idea to me, because if we leave the focus in Recent (or mine or a document type) while searching it will look like that we are searching only in that particular section, which is not true.

Then, I think that we should leave it as it is, because although it may seen confusing to switch to Home, it's even more confusing to let the user stay in the section that he is but display everywhere results.

Let me know if you guys have any question or if there's anything that I misunderstood.

Thanks

**Comment by kayleen-lim** [comment]
Hi @sergiogonzalez 
In that case, do you think there should be some way of letting the user know that the search is not based on the results that they are currently viewing, but on all the documents?
Thanks!

**Comment by sergiogonzalez** [comment]
Hey @kayleen-lim 

We don't display that anywhere in the portal UI (I think it should be in the official documentation). A hint about this is that the focus is moved to Home or to the folder where the user is, so the user can guess that he's not searching in a specific document type, or in "Mine" or "Recent"

**Pull request closed without merging**
