### PR TITLE
LPS-67795 PDF previews generated with ImageMagick&Ghostscritpt are not properly sized

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

Could you please check this pull request?

It relies on PDFBox in determining the width and height of the PDF pages because Java has no built in PDF processing capabilities.

Best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 

Looking at your explanation and the LPS ticket I understand that the issue is that Ghostscript needs both width and height because otherwise it will use the default value (which it seems it's 1000 for the height) and we don't want that.

However, I don't know if Ghostscript needs the exact value or the max value. Because if it works with the max value we could use a very big value (like `Integer.MAX_VALUE`) when the value set in the portal.property is 0?

If that works we would avoid doing the calculation of the width/height.

Thoughts?

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

According to the description in the LPP linked to the LPS, the behavior of GhostScript is rather strange.

> It seems that when max.width is greater than 792, its value will be used for the height, and the width will be 792. When it is smaller, it will be correctly used as the width, but the height will always be 792. If both properties are set (and IM is enabled) the they are used without any adjustment for the aspect ratio, and they are also switched.

My tests showed that the dimensions will be the same as conversion done with PDFBox only in the case when we explicitly set -dDEVICEWIDTH and dDEVICEHEIGHT.
If one of them is absent, the strange switching behavior will occur.

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 

I found a little weird this line https://github.com/sergiogonzalez/liferay-portal/pull/3439/commits/121446ed3ba96b50453819c5efbbdf673f7ad038#diff-7214810480a4b28c8e175fb23142ad4aR868 and the next one.

Why do we need to multiply the heightFactor by the width? Shouldn't they be heightFactor and height?

Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

The reason of this that we should calculate a width or height (whichever is absent) that is proportional to the other dimension.
In other words, we need a width that is proportional to the height and vice versa.

I applied the logic from _ImageToolImpl.scale(RenderedImage renderedImage, int width)_

```
		int imageHeight = renderedImage.getHeight();
		int imageWidth = renderedImage.getWidth();

		double factor = (double)width / imageWidth;

		int scaledHeight = (int)Math.round(factor * imageHeight);
		int scaledWidth = width;

		return doScale(renderedImage, scaledHeight, scaledWidth);
```

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42954. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/27996f5~1...27996f5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
That makes sense. Thanks @IstvanD 👍

**Comment by IstvanD** [comment]
Sure.
Thanks for forwarding :+1:

**Pull request closed without merging**
