### PR TITLE
LPS-57178 Create single test for each case (in order to throw all the test and assert all the cases work)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/269. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
