### PR TITLE
productivity center improved approach for JSP support

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
Hey @sergiogonzalez here are some changes I would recomment for productivity center's `UserPersonalPanelLayoutController`. This way you don't have to worry about the path to your resources. You simply dispatch requests to your `ServletContext`.

I will be adding a convenience API to reduce the boilder plate even more. I'll let you know what I have that.

**Comment by sergiogonzalez** [comment]
Thanks Ray for letting us know.
@adolfopa can you include this changes in the personal space?

**Comment by adolfopa** [comment]
Done, see https://github.com/brianchandotcom/liferay-portal/pull/24667

Thanks Ray!

**Comment by sergiogonzalez** [comment]
Closing it.

**Comment by rotty3000** [comment]
FYI, I figured out a way to reduce almost all the boiler plate for getting
the ServletContext

I will send you guys another PR with change so you can familiarize
yourselves with it as soon as I get a chance.

On Tue, Mar 10, 2015 at 12:54 PM, Sergio Gonzalez <notifications@github.com>
wrote:

> Closing it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergiogonzalez/liferay-portal/pull/2021#issuecomment-78097119>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Pull request closed without merging**
