### PR TITLE
LPS-75573 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
Hey @daviddotzhang and @hhuijser we need an integration test to validate this change. Could you please add a new test in DLFileEntryFinderTest class that tests this?

We should also make consistent the SQL queries (the countBy has a linebreak and the findByG_U_F is in the same line)

Thanks

**Comment by zsigmondrab** [comment]
Hi @sergiogonzalez ,

could you please give us an example that we can use to create such test with little modification? Is there any existing test like this?

Thanks,
Zsigmond

**Comment by sergiogonzalez** [comment]
Hey @zsigmondrab 
We should include the test in DLFileEntryFinderTest that it already exists and contains some tests. 

According to the ticket description, I think it should be enough if we add a file entry using a file entry with workflow (take a look at https://github.com/liferay/liferay-portal/blob/master/portal-test-integration/src/com/liferay/portlet/documentlibrary/util/test/DLAppTestUtil.java#L42 and the `approved` parameter should be false.

Then, modify the file entry as if it was in a workflow step using `DLFileEntryLocalServiceUtil.updateStatus`. 

We should assert that with the new changes the finder is able to return the file entry.

And please make sure that the test fails if the fix is not included to avoid creating a happy test.

Thanks

**Comment by daviddotzhang** [comment]
@sergiogonzalez ,
the main cause is that.  the **userId** in the DLfileVersion table is updated to a different one. as a result, it can be searched using the default SQL. 

1: I am not sure if we need to create a document for review, then approved it.   according to my simple test, the suggestion from you might increase the count of the fileEntries, this will break the other test cases. Need I to change the other broken test cases?

2: How about just change the value of the userId and userName in dlFileVersion ""FE2.pdf"" directly. ?

**Comment by sergiogonzalez** [comment]
Hey @daviddotzhang 
The logic to add the document for review and then approved it I wouldn't do it in the test itself (not in the setup) to avoid breaking other tests. We shouldn't need to modify the behaviour of other tests as long as we make sure that whatever data we need to add, we do it only for our test, and we delete when the test is run.

Thanks

**Pull request closed without merging**
