### PR TITLE
LPS-84256 Keep the original modified date when updating the viewCount

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by github-vacation** [comment]
I'm currently on vacation and I'll be back August 17th. 
Please, feel free to send this pull to @4lejandrito and he'll take care of it while I'm gone.
Thanks!

**Comment by github-vacation** [comment]
I'm currently on vacation and I'll be back August 17th. 
Please, feel free to send this pull to @4lejandrito and he'll take care of it while I'm gone.
Thanks!

**Comment by hudakl** [comment]
Hi,

Was this pull forwarded?
If not, could you please review the changes?

Thank you,
Laci

**Comment by robertoDiaz** [comment]
See https://github.com/sergiogonzalez/liferay-portal/pull/4583

Sorry, I miss this one.

**Pull request closed without merging**
