### PR TITLE
LPS-69483 Apply also to Wiki and Message Board

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @IstvanD

**Comment by sergiogonzalez** [comment]
Hey @robertoDiaz @IstvanD,

I don't think that this is the proper fix because removing everything after the ? sign seems too much.  
Why don't we change in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/LayoutURLUtil.java#L46 the method invocation so we invoke `PortalUtil.getLayoutURL(layout, themeDisplay, false)` so the doAsUserId is not included in the url?

I think that should fix the issue and it seems safe because that class is only used in the places where we don't actually want to have the doAsUser information.

I think that's the best approach, but in case it doesn't work, we can always use `HttpUtil.removeParameter` and remove the `doAsUserId` because that's always safer than removing everything after `?`

Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez @robertoDiaz 

Thank you, you are absolutely right.
Not only it is a much smaller change, but solves the issue for Blogs, Messages and Wikis the same time.

I submitted the pull to Roberto
https://github.com/robertoDiaz/liferay-portal/pull/530

**Comment by robertoDiaz** [comment]
Looks good to me.

If you have test it I could fwd it to sergio directly.

Are you ok with this?

Thanks!!

**Comment by IstvanD** [comment]
I've sent it to @sergiogonzalez 
https://github.com/sergiogonzalez/liferay-portal/pull/3814

**Pull request closed without merging**
