### PR TITLE
LPS-68780 setting comment to request

### PR DESCRIPTION
**Pull request by marcellustavares**
@sergiogonzalez, could you help me to review @linolaoj 's fix? It's related to comments.

Thx

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @linolaoj @marcellustavares 

I was reviewing the pull but I don't fully understand why we need to set the comment as a request attribute beause it seems that it's already done by the `CommentAssetRenderer.java` class in 

```java
	@Override
	public boolean include(
			HttpServletRequest request, HttpServletResponse response,
			String template)
		throws Exception {

		Comment comment = CommentManagerUtil.fetchComment(
			_workflowableComment.getCommentId());

		request.setAttribute(WebKeys.COMMENT, comment);

		return super.include(request, response, template);
	}
```

So maybe the issue is that when the comment is being rendered in the workflow using the asset, the method `include` of the assetRenderer is not being invoked?

I don't think that we should leave the code in the portlet, checking if the there's an attribute in the request, and if there's not, add it at that point, because we are duplicating the same logic as in the AssetRenderer.

So I think that we need to fully understand why we need to put that logic there, and if we do need to include it at a portlet level instead of the asset level, we should remove the logic that adds the method from the AssetRenderer so we only leave it in the portlet.

Actually, if that's the case, we should add that new logic to MVCRenderCommand classes like EditDiscussionMVCRenderCommand.java and adapt the urls to use mvcRenderCommandName to match the new render command.

Let me know if you guys have any question or if there's anything that I misunderstood.

Thanks guys!

**Comment by marcellustavares** [comment]
thx for the review @sergiogonzalez. @linolaoj can you take a look at this?

Regards

**Comment by linolaoj** [comment]
Ok, I'll look into this and resend. 
Thanks!

**Comment by linolaoj** [comment]
Hi @sergiogonzalez,
I agree that it is not good to have the code duplicated and the steps below show why the include from CommentAssetRenderer is not being called:

1- On edit_workflow_task.jsp it uses a taglib to display the asset, the taglib calls the include from CommentAssetRenderer (at this point the comment is on the request attribute).
```
       <liferay-ui:asset-display
				assetRenderer="<%= assetRenderer %>"
				template="<%= AssetRenderer.TEMPLATE_ABSTRACT %>"
				/>
```
2-  On the same jsp, we ask the assetRenderer for the editURL, then  CommentAssetRenderer returns a url that points to edit_discussion.jsp.

3- edit_discussion.jsp does not use assetRenderer, so the comment attribute is never set when the editURL is accessed.

Given this scenario, which way do you think would be better to fix the issue? Should I create the MVCRenderCommand classes?

Thanks :)

**Comment by sergiogonzalez** [comment]
Hey @linolaoj 

Thanks for explaining the issue with such detail :)

I think that the best approach is to create a new MVCRenderCommand and that command is responsible of adding whatever is needed by the JSP to render. 
We will need to leave the logic duplicated in the include method because that's used to render the jsps discussion_abstract.jsp and discussion_full_content.jsp.

Let me know if you have any other question.

Thanks!

**Pull request closed without merging**
