### PR TITLE
[TECHNICAL-SUPPORT] LPS-67377

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @BryanEngler @jonathanmccann 

I don't fully understand the change in this pull. Could you elaborate a little bit more what is the issue with Internet Explorer? Do you have a link where it's explained?

I'm assuming that when the file is uploaded Internet Explorer indicates that the mime type of the file is image/x-ms-bmp but when that same file is served to the server with the mime type image/x-ms-bmp Internet Explorer cannot understand it?

According to the LPS we need to set the following property:

`
mime.types.web.images=image/x-ms-bmp,image/bmp
`

Are both image/x-ms-bmp and image/bmp necessary?

I don't like the idea of hardcoding some conditionals in the portal source code to support a use case that it's not even in the default portal.properties values...

Thanks!

**Comment by jonathanmccann** [comment]
Hey @sergiogonzalez 

I can't speak to your other questions about the issue itself, but the fix is the exact same as the fix for https://issues.liferay.com/browse/LPS-62517 / https://github.com/sergiogonzalez/liferay-portal/pull/3027/commits/b72332bb1a01a2496b0190fc95c81ea5cdac6066 and they both seem to resolving similar issues.

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann yeah, I think you're right. Could you guys reply to my questions and send the pull to @adolfopa since he's the one who fixed LPS-62517 ?

Thanks!

**Comment by BryanEngler** [comment]
Ya the issue with IE is explained in LPS-62517, and your assumption is correct.

As far as the property goes, only image/x-ms-bmp is necessary. Should we append it to the property as a another default value?

**Comment by BryanEngler** [comment]
forwarded pr https://github.com/adolfopa/liferay-portal/pull/304

**Pull request closed without merging**
