### PR TITLE
LPS-74197 gradlew npmShrinkwrap - collaboration

### PR DESCRIPTION
**Pull request by robframpton**
Hey @sergiogonzalez,

Just regenerating the `npm-shrinkwrap.json` files in order to update `liferay-module-config-generator` to a more stable version.

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
Same thing for adaptive media sub repo: https://github.com/sergiogonzalez/com-liferay-adaptive-media/pull/187

**Comment by Robert-Frampton** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
thanks @Robert-Frampton for letting me know 👍

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/51060. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/94604d6~1...94604d6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
