### PR TITLE
[SEE DESCR] LPS-60902 Separate trash logic from main DM service (part 1)

### PR DESCRIPTION
**Pull request by adolfopa**
This is the first of two PRs for LPS-60902. In this one I clean up and refactor some of the code.

NOTE: https://github.com/sergiogonzalez/liferay-portal/pull/2736 depends on this.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33009. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
@adolfopa he hecho unos cambios en la pull antes de enviársela a Brian. Puedes ver que estén bien?
https://github.com/brianchandotcom/liferay-portal/pull/33009

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
