### PR TITLE
LPS-76857 Fix compile error

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Pushed to upstream

cc/ @brianchandotcom

**Comment by jpince** [comment]
@drewbrokke fyi, this fixed the error caused by https://github.com/liferay/liferay-portal/commit/8d5f5a13834649f7468120dff5770b918d04de56 (just so you know what code changes occurred after your pull was merged :) )

**Comment by drewbrokke** [comment]
Thanks for the heads up, @jpince. Thanks for fixing this, @ealonso!

**Pull request merged**
