### PR TITLE
LPS-55685

### PR DESCRIPTION
**Pull request by dustinryerson**
@eric-chi @Preston-Crary

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @sergiogonzalez,

This is an update for [LPS-55685](https://issues.liferay.com/browse/LPS-55685).

Please let @eric-chi, @Preston-Crary or myself know if you have any questions.

Thanks!

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @eric-chi @dustinryerson 

Can we instead of just saying "is not a valid score" do something else like "should be between 0 and 1".
I think that provides more information? What do you guys think?

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/eric-chi/liferay-portal/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
