### PR TITLE
[TECHNICAL-SUPPORT] LPS-60013

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler @mbowerman

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mbowerman** [comment]
Hey @sergiogonzalez,

I'm not sure I understand your point about the `getAssetRenderer` method. As I understand it, the `getAssetRenderer` method will return a valid page as long as the correct arguments are passed in. The reason that it wasn't returning a valid page before my proposed fix is because the incorrect type parameter was passed in - we were passing in `TYPE_LATEST_APPROVED` instead of `TYPE_LATEST`.

If we were to continue allowing the taglib to pass in `TYPE_LATEST_APPROVED`, we would have to modify `getAssetRenderer` in such a way that it can return a pending article even when `TYPE_LATEST_APPROVED` is passed in. That's why I think it makes more sense to edit the taglib so that it passes in the correct type parameter, rather than modifying the `getAssetRenderer` method.

**Comment by sergiogonzalez** [comment]
Hey @mbowerman 

The thing is that right now it seems that there are inconsitencies with the way the Asset are implemented with the different portlets. In Journal it returns a non approved JournalArticle even though the TYPE_LATEST_APPROVED is passed as an argument.

So, to be honest, I'm not totally sure about what is the expected behaviour here. Should the Asset framework return `null` if there's no approved entry ant TYPE_LATEST_APPROVED is passed? Should it return an asset even though is not approved (like Journal)?

I think that we should clarify what is the general rule for that kind of scenarios and once we have agreed on that we can decide whether we need to modify the `getAssetRenderer` method or not. 

I think that you should ask somebody from the WCM team (@juliocamarero @ealonso @epgarcia) since they maintain the Asset Framework (and actually the taglib was created by @ealonso) so they can define what is the expected behaviour here.

**Comment by mbowerman** [comment]
OK, I've modified the `getAssetRenderer` method so that it will return a valid file entry even when TYPE_LATEST_APPROVED is passed in. While I was at it, I also added some logic for it to throw an IllegalArgumentException if an invalid type argument is passed in (to make it consistent with the `getAssetRenderer` method from the DLFileEntryAssetRendererFactory class).

I sent a pull request to @BryanEngler. But I have not discussed this with anyone from the WCM team yet, so I (or somebody) should probably do so to make sure that this is the way the `getAssetRenderer` methods are supposed to work before this gets approved.

**Comment by sergiogonzalez** [comment]
Sounds good, can you guys send the pull to @ealonso for final review?

**Pull request closed without merging**
