### PR TITLE
LPS-60682 Setter does nothing

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ESta pull ya ha pasado los test:

https://github.com/sergiogonzalez/liferay-portal/pull/2756

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33326. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
