### PR TITLE
LPS-76348 [TECHNICAL SUPPORT]

### PR DESCRIPTION
**Pull request by jcampoy**
Hey @sergiogonzalez ,

@jbalsas let us know that we can not recover the information in this kind of form fields.

Blogs, Message Board and Knowledge Base have a similar issue, we can try to fix it through other tickets but firstly I want to test if this kind of improvement is valid for our UX, or may be we want to  maintain the current behaviour.

Could you take a look? this is how it looks:

Regards.

screen shot 2017-12-11 at 17 28 20

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jcampoy** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/jcampoy/liferay-portal/pull/48. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/efd13fd~4...efd13fd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
