### PR TITLE
LPS-78083 Simplify

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by laszlopap** [comment]
ci:reopen

**Comment by laszlopap** [comment]
ci:test

**Comment by laszlopap** [comment]
Hi @sergiogonzalez ,

Did you have any time to check the PR?

Thanks,
László

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56091. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @laszlopap I just sent it to Brian. Thanks!

**Comment by sergiogonzalez** [comment]
Hey @laszlopap can you please update the ticket https://issues.liferay.com/browse/LPS-78083 to a bug instead of a task? Or is there any reason why it's a task and not a bug? Thanks
cc/ @robertoDiaz

**Comment by laszlopap** [comment]
Hey @sergiogonzalez ,

Thanks for the fast reaction. I have changed the LPS to Bug.

Regards,
László

**Pull request closed without merging**
