### PR TITLE
LPS-79492

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/676. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/0e801b7~2...0e801b7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
