### PR TITLE
LPS-55716

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same pull than https://github.com/sergiogonzalez/liferay-portal/pull/2193 but I have added the update treepath at mergeFolders for Bookmarks and Journal.

@juliocamarero

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/405. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
