### PR TITLE
LPS-53227 New finder and service method for DLFileEntry

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Sergio,

I'm implementing a performance fix for staging, namely deferred indexing. That means we are pausing the indexing processes during the publication process, and when we have finished we are reindexing the imported entities.

For that, I'd need this new finder and service method in DL. It's quite simple, and Brian reviewed this for 6.2, I've applied his SF to here as well.

Thanks,

Máté

### CODE REVIEW

**Comment by matethurzo** [comment]
It seems like these test fails are not related to the change

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23686. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @matethurzo 

Could you please add some tests for the finder?
I have sent the pull to Brian: https://github.com/brianchandotcom/liferay-portal/pull/23686

Thanks!

**Pull request closed without merging**
