### PR TITLE
LPS-62253  Add title bar an the add button

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/sharonchoi/liferay-portal/pull/416. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
