### PR TITLE
[TECHNICAL-SUPPORT] LPS-63646

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by AngeloJ** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by ChrisKian** [comment]
Hi,

Looking at the failed tests, they deal with Wiki, modifying folders, and webcontent workflows respectively.  My fix simply changes which version of a document is rendered via it's latest locale.  Furthermore, my change only affects a .jsp file, and has nothing to do with deleting, editing, or workflows. 

Let me know if you have any questions.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37036. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
