### PR TITLE
LPS-68550 Extract render logic to BaseKBPortlet

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by adolfopa** [comment]
@sergiogonzalez Can you send this pull to @sharonchoi after you finish the review? This will probably break some functional tests.

**Comment by sharonchoi** [comment]
@sergiogonzalez I've fetched this PR, and am running KB tests hacking the pr-tester here: https://github.com/sharonchoi/liferay-portal/pull/935, to check any potential UI changes/POSHI failures.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/sharonchoi/liferay-portal/pull/943. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/0d85b27~1...0d85b27) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @sharonchoi I have sent you the final pull ready to send it to Brian https://github.com/sharonchoi/liferay-portal/pull/943.

Once you're done with your tests, please send it to Brian to merge it and include it in the release.

Thanks

**Pull request closed without merging**
