### PR TITLE
LPS-60671 Create a new object that will contain all the logic not related with the MenuItem creation but necessary

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/389. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
