### PR TITLE
LPS-61965 Add history information

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
This is likely failing due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34370. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/189. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
