### PR TITLE
LPS-53136 Refactor creole wiki engine to make it use the common layer for <liferay-ui:input-editor> based wiki engines

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Rename module to *-web. Split in 2 different pulls: first one is only API changes in Engine and apply that to all engines. Copy/paste in single commit and different commit for implementing API changes in engines. Remove Export-package blank. Fix up Language.properties.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/izaera/liferay-portal/pull/105. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
