### PR TITLE
LPS-59122

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Sergio,

I went ahead and  removed all the *ServiceUtil calls in the Collaboration components.

This was all done by an automated script. Everything compiled and from looking at it (and we'll see if it passes the tests), I didn't see any obvious issues, but it does need to be reviewed manually carefully.

If you don't think this is helpful and it will only cost you more time (or if the quality of this is just complete rubbish), feel free to disregard this pull request... I just wanted to test my script :)

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @hhuijser 

This was really really helpful :)

I have sent all the commits to Brian except Wiki Service and Wiki Web because we are working on those and it would create conflict errors. 
Considering that this is a script that we can run when we need to, I will send first the manual changes for wiki web and wiki service and once they are in master, could you please run the script and send me a pull with the changes?

For the other commits here are the pulls I sent to Brian

https://github.com/brianchandotcom/liferay-portal/pull/31151
https://github.com/brianchandotcom/liferay-portal/pull/31153
https://github.com/brianchandotcom/liferay-portal/pull/31154
https://github.com/brianchandotcom/liferay-portal/pull/31155
https://github.com/brianchandotcom/liferay-portal/pull/31156
https://github.com/brianchandotcom/liferay-portal/pull/31157
https://github.com/brianchandotcom/liferay-portal/pull/31158

I'll close this pull for now until we are done with the wiki and then I'll get back to you.

Thanks for the script once again :)

**Comment by hhuijser** [comment]
Hey @sergiogonzalez 

Sounds good.
Just FYI, these two are breaking tests:
brianchandotcom#31151
brianchandotcom#31154

Seem like simple NPEs that should be easy to fix...

**Pull request closed without merging**
