### PR TITLE
LPS-73480

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/2913 for some discussion on the fix

**Comment by yuhai** [comment]
Hi @sergiogonzalez 

Hope you are well.

Since the issue came from EE customer. Could you please review this PR when you have time?

Regards,
Hai

**Comment by sergiogonzalez** [comment]
Hey @yuhai 

I understand the issue you are trying to fix but I have some concerns about this pull:

1. In this kind of pulls it's better if you guys send it with some tests that ensure that the feature was broken before the fix and that the fix actually fixes the issue and make the test pass. Could you please add an integration test for this use case? Basically ensure that there shouldn't be any workflowIntanceLink when deleting a file entry that has a version pending review. The test should fail without your fix and it should pass with your fix.
2. Taking a deeper look at this logic, there's another bug that will happen once you fix this one. With your fix, the oldFileVersionStatus variable of https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppHelperLocalServiceImpl.java#L1372 will be pending. That status will be stored in the trashEntry according to https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppHelperLocalServiceImpl.java#L1391. That information will be used when the file entry is restored from the recycle bin, so if the document is restored, the status will be PENDING but it won't have any workflowinstancelink associated to that file version, which is wrong. I have compared this logic with the one in JournalArticleLocalServiceImpl (because it's the same scenario) and it seems that  they fix this scenario with this lines https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L3681. They basically set the status to DRAFT if it was pending, so in case the article is restored it will be restored as DRAFT and not pending, which is ok. Could you please also check and fix this? We should also create a test for this that should ensure that when a file entry with a pending version is moved to the recycle bin and then restored, the last version has a DRAFT stauts and not a PENDING one.

Let me know if you have any questions @yuhai 
Thanks!

cc/ @hhuijser

**Comment by yuhai** [comment]
Hi @sergiogonzalez 

Yes. I will do this.

Regards,
Hai

**Pull request closed without merging**
