### PR TITLE
[TECHNICAL-SUPPORT] LPS-71134

### PR DESCRIPTION
**Pull request by Alec-Shay**
/cc @SamZiemer @jonathanmccann

Re-sending from https://github.com/sergiogonzalez/liferay-portal/pull/3850 with the changes you mentioned.

I implemented an integration test for a standard export/import between sites with default data. I also somewhat wanted to make the test more robust by including imports with different import strategies, but I knew at least in one case this would fail due to known bugs. For instance, see: [LPS-71177](https://issues.liferay.com/browse/LPS-71177).

Please let me know if there are any other problems with this to be addressed. Thank you.

For notes from the previous pull, please see: https://github.com/SamZiemer/liferay-portal/pull/209#issue-213202592

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay the pull looks good to me.
I'm going to fwd it to @matethurzo so he can check the test as it affects staging and I want to make sure that the approach is right.
Thanks

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1632. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Alec-Shay** [comment]
@sergiogonzalez Sounds good to me. Thanks.

**Pull request closed without merging**
