### PR TITLE
LPS-78198 Mine Filter on Bookmarks Locks When There are no Bookmarks that you've created

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-78198](https://issues.liferay.com/browse/LPS-78198).<br><br>Hey @sergiogonzalez, I'm sending this to you for now, but if there's a better person, please let me know.  Thanks!<br><br>/cc @pei-jung, @alexandervalencia, @JoshuaStClair

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test

**Comment by drewbrokke** [comment]
ci:stop

**Comment by drewbrokke** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55706. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/3a8c8cb~1...3a8c8cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
