### PR TITLE
LPS-58183

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Two issues: LPS-58183 & LPS-58446

**Comment by zxdgoal** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
hey @zxdgoal @hhuijser it seems that this pull doesn't compile? Can you resend? Thanks!

**Comment by hhuijser** [comment]
Oops

**Comment by zxdgoal** [comment]
Will resend later

**Pull request closed without merging**
