### PR TITLE
[TECHNICAL SUPPORT]LPS-61179 Getting all subfolderids is very inefficient in select_folder.jsp

### PR DESCRIPTION
**Pull request by zsolah**
Hi Sergio,
I have used the same pattern as here: https://github.com/brianchandotcom/liferay-portal/commit/c3662933fb8328c5b5e7a1e0906cee554b856641#diff-9ba19a23ef33fb9eb07423c44734ed60R241 

Please review.

Thanks,
Zsolt

### CODE REVIEW

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34081. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
