### PR TITLE
LPS-52122 - Fix for the broken test of DLFileVersionTest class.

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @marcellustavares sorry for the delay in the review. I just sent it to Brian. Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23827. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcellustavares** [comment]
Thanks @sergiogonzalez :)

**Pull request closed without merging**
