### PR TITLE
[TECHNICAL-SUPPORT] LPS-75133

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @mbowerman @jonathanmccann 

This upgrade that belongs to the notifications-web module shouldn't use queries to manipulate data of UserNotificationEvent table. The reason is because of modularity and because we can evolve separately the service from the web module. UserNotificationEvent services are in core and they follow the release of the portal. notifications-web is a module that has a different and independent release lifecycle. 

If we use the sql queries to manipulate the data of the core, we are having a very tight contract with the core that can be broken at anytime if the core removes/renames/updates a table or field of the database. Notifications-web portlet shouldn't know any internal detail of UserNotificationEvent, and the tables, fields, etc are internal details of the core. Instead, we should use the well defined api proposed by the services of the core. 

The only exception to this rule, is when we are manipulating data that is defined by the module itself. For example, blogs-service module could have an upgrade that manipulates the BlogsEntry table directly using sql queries. That's ok because everything is self contained and there's not coupling between modules. However, if blogs-module needs to do any kind of browsing or manipulating of BlogsEntry table, it should do it via services, because that's the API that it's allowed to use.

Thanks

**Comment by mbowerman** [comment]
Hi @sergiogonzalez,

I see that you're referring to the "Golden Rule" of coding upgrade processes listed in [this Grow Article](https://grow.liferay.com/people/DXP-+How+to+code+upgrade+process+and+backport+rules). The Golden rule mentions that you should generally try to avoid directly interacting with other modules' sql tables, as you said. However, please see the following section:

https://grow.liferay.com/people/DXP-+How+to+code+upgrade+process+and+backport+rules#section-DXP-+How+to+code+upgrade+process+and+backport+rules-Exception

> This rule is mandatory for 99% of the cases. In a few cases the upgrade process needs to handle a huge amount of data so using the API could seriously impact the performance. For those case we can consider use just SQL statement even with tables which don't belong the module we are modifying. Here is an [example](https://github.com/achaparro/liferay-portal-ee/blob/f6ca2a44a39fca06049a4228a73e898aab54cdfe/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v1_0_2/UpgradeJournalDDMTemplateLinks.java#L34) we defined a query which joins internal tables (journalArticle) with external tables (DDMTemplateLink) because we dealt with all journalArticle records and we proved that the performance was incredible better (see commit message).

In this case, the performance impact is huge from updating the UserNotificationEvent table in bulk instead of updating it one by one. In my own testing, I saw that my changes caused it to take 3 seconds to complete, whereas before it was taking 10 minutes. 10 minutes may not seem like that long of a time for an upgrade process, but we have a client for whom this upgrade process is taking over 4.5 hours. For many users that have used the Notifications Portlet and have widely used portals, this process will likely take a comparable amount of time, since it is reasonable to expect there to be millions or even tens of millions of UserNotificationEvent entries in a widely used portal.

**Comment by mbowerman** [comment]
Hi @sergiogonzalez,

I've also discovered that we are already fetching from the UserNotificationEvent table later on in the upgrade process (https://github.com/jonathanmccann/liferay-portal/blob/5cc5254762e7fbe7b4f64c536a95f65062b8e3bf/modules/apps/collaboration/notifications/notifications-web/src/main/java/com/liferay/notifications/web/internal/upgrade/v2_1_0/UpgradeUserNotificationEvent.java#L71-L73). If you still believe that we should avoid interacting with the UserNotificationEvent table directly, then shouldn't we remove this usage of it too?

**Comment by sergiogonzalez** [comment]
Hey @mbowerman 

I have talked to @achaparro and we can make an exception on this case because as you stated the UserNotificationEvent table might contain lots of rows.
However, in order to reduce the possibility of future bugs because the table and the model exist, we think that it's a good practice to include some tests that ensure that the table and the column that are queried in the database exist, so in case anyone drops the table or column necessary for the upgrade, the test will fail. 
This test should be an integration test (we need to access the database) so we might need a  new module notifications-web-test (although Brian might change this to another module name). Ideally we should reflect in the test (via a comment or in case the test fail with a log message) that it ensures that the upgrade will work.

For the test, we shuold be able to obtain a database connection from:

`Connection con = DataAccess.getUpgradeOptimizedConnection()` and then obtan a `com.liferay.portal.kernel.dao.db.DBInspector` that contains the necessary methods to ensure that the table and column exists, even with the right content type.

Thanks

**Pull request closed without merging**
