### PR TITLE
LPS-73550 build lang

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hey @sergiogonzalez 

Any update on this?

Thx!

**Comment by robertoDiaz** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/640. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/e51d512~2...e51d512) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
