### PR TITLE
LPS-54438 Minor changes

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
cc/ @JorgeFerrer

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25202. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary 

I sent the pull to Brian. The only change that I did is related to https://github.com/Preston-Crary/liferay-portal/commit/15ebc5b3646a5eba1be6b5b65b8411cfa9422aa4. We shouldn't expose the permission checking outside the remote service because that duplicates logic and makes it harder to maintain (if the permission check changes to do a different check or an extra check nobody will remember to change that piece of code so it's better if it's all encapsulated in a single method)

The other option was to create a fetch method in the remote service, but since it would be something new and it's not clear how it should behave (return null if the user doesn't have permission? Throw the exception if he doesn't have permission and we would need to do the catch anyways?) I just left it as it was before. 

One more option was to be more specific in the Catch, so instead of catching every exception do it for more specific exceptions (like PrincipalException and NoSuchFileEntryException in this case).But since it's already catching Exception, if we remove it for more specific exceptions that block of code could throw now exceptions that before it wasn't, and after thinking it a little bit more it seems like it's more risky to have specific exceptions than having Exception (since it always had Exception)

Let me know if you have any question or if I didn't explain myself properly

Thanks!

**Comment by Preston-Crary** [comment]
That makes sense, thanks for the explanation.

**Pull request closed without merging**
