### PR TITLE
[TECHNICAL-SUPPORT] LPS-79505

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @SpencerWoo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by SpencerWoo** [comment]
Hi @sergiogonzalez, any update on this?

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann @SpencerWoo 

I was trying to reproduce the issue described in the https://issues.liferay.com/browse/LPS-79505 and I couldn't reproduce the issue.
I could successfully align the image and it was preserved when switching from wysiwyg to code view and also when saving the blog entry.

Can you retest it and if you guys can still reproduce it resend me the pull and updating the steps in the LPS ticket?
Let me know if there's anything that I'm missing here.
Thanks

blog_alignment

**Comment by SpencerWoo** [comment]
@sergiogonzalez That gif does show the proper behavior but I can still reproduce on 090b2d4baf23a17e8cb2a98646c7e49f307a7dbf.  What commit is the issue no longer reproducible?  (I tried grabbing the latest commit but I'm having deployment errors)

**Pull request closed without merging**
