### PR TITLE
LPS-67752

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Sergio,
Could you help to review this pull request? it is for a ee customer

**Comment by sergiogonzalez** [comment]
Hey @daledotshan @daviddotzhang 

I think that the order should be:

1. First we should order by modelCategory. MBCategory should always be displayed before than MBThreads. This is the same behaviour as in Documents and Media, where folders always go before than documents.
2. Then priority: if a thread is flagged as Urgent, it should always be displayed before other threads not marked as urgent, even if it was published long time ago.
3. Last Post Date should be included here. However, I think that the lastPostDate should apply only to MBThreads and not to MBCategories. For MBCategories we should order based on the name (alphabetical order) and not based on last post date. We want categories to be displayed in the same order always (no matter when it was published).

We don't want to hardcode the ordering of the lastPostDate in the finders or sql. We should use a Comparator for it. In Control Panel, Message Boards doesn't offer any ordering mechanism, but we want to implement one, and if we hardcode "lastPostDate" in the finder or sql it will be harder to apply ordering in Control Panel.

Take a look at how it's done in Document Library, where we have the same situation with folders and we want folders to always appear first. We should create some comparators that order for more than one field, as it's done in RepositoryModelSizeComparator.java https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/document/library/kernel/util/comparator/RepositoryModelSizeComparator.java for example.

Then, the finders should have a default ordering but it should be replaced by the comparator (in case it's passed as an argument). See line 467 and 475 here https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFolderFinderImpl.java#L475. We should do the same in MBCategoryFinderImpl.

Finally, in order to make sure that this is working and that it doesn't break, we should add some integration tests that ensure that the ordering is working in MBCategoryLocalServiceTest.

Let me know if you guys have any questions.

Thanks!

**Comment by daviddotzhang** [comment]
Hey  @sergiogonzalez ，

According to https://github.com/brianchandotcom/liferay-portal/pull/33460, I think we have implemented  a new function , the threads and categories can be queried by on SQL. 

For 1,  as we have modelCategory, thread -> modelCategory =0,  modelCategory =1
           it will impact the order of category and thread.

For 2, yes. Thanks, 

**For 3.  this is much like a new future ,  from my perspective,  
 a:  I will add a list box to the UI , which is same as the DM and WCM, "modified date", "priority", "name" 
 b:  I will add new comparators based on "modified date", "priority", "name".
 c:  At last I will implement the whole function.**

Is this OK  for you ?

Thanks,
David.

**Comment by sergiogonzalez** [comment]
Hey @daviddotzhang 

Yeah, I think it sounds good.

Regarding 1 we will need to do something to ensure that the categories are not ordered by last post date. I talked to David (the Collaboration UX guy) and he agreed that the threads should be ordered by modified date while the categories should be ordered alphabetically.

If you find issues doing that, feel free to send me a pull and I'll help you there.

It would be great if we can also add some integration tests to ensure that the query is working as well as the order.

Thanks

**Pull request closed without merging**
