### PR TITLE
LPS-58854 apply search container changes

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
@jbalsas I have updated all the affected methods in Journal (move doesn't work!)

@sergiogonzalez can you apply this to the DL? I am not sure which methods should be updated (I have debugged all the methods in Journal to verify this change).

thanks!

**Comment by juliocamarero** [comment]
@jbalsas I have fixed the compilation issues and also fixed the issue with move. It works 100% in Journal now.

@sergiogonzalez can you apply this to the DL? The move part is the trickiest one. You can copy the changes from Journal.

thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by jbalsas** [comment]
:dancer: :dancer: @juliocamarero you're awesome!! :heart_eyes: :heart_eyes:

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32343. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
