### PR TITLE
LPS-76893 Images appear rotated in content

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @sergiogonzalez 

Could you please review this pull request?
This fix ensures an image preview is selected instead of the original image, which may be not properly processed, for example, it has a wrong EXIF orientation.

Thank you and have a nice weekend!

Bests,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

I was wondering if you could find the time to have a look at this pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by sergiogonzalez** [comment]
Hey @IstvanD I'll review this one tomorrow.
Sorry for the delay.

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

No problem. Thank you for your answer, I'm looking forward for the results.

Best regards,
István

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61502. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/b6c34ad~2...b6c34ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Sorry for the delay @IstvanD 
I just sent it to Brian
Thanks

**Comment by IstvanD** [comment]
No worries @sergiogonzalez 
Thanks for forwarding!

**Pull request closed without merging**
