### PR TITLE
[TECHNICAL-SUPPORT] LPS-59007

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ericyanLr** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann @BryanEngler @ericyanLr 

I'm not 100% sure about this change, so I have sent an email to @rotty3000 so he can double check it because he was the original developer of this portlet.

I'll keep you updated

Thanks!

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann @BryanEngler @ericyanLr

I'll fwd this pull to @rotty3000 so he can take a look at this when he has the chance.

Thanks guys

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/rotty3000/liferay-portal/pull/1050. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
