### PR TITLE
LPS-70834

### PR DESCRIPTION
**Pull request by mmariuzzo**
Hi Sergio,

I was not satisfied by the previous PR from the other branch because the rebase duplicate the commits.
So I've redo my commits in a new branch.

It also contains the fourth idea: extends PDFProcessorImpl to use converters registered as Component

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @mmariuzzo thanks for sending this. I didn't have much time to review it yet, but I'll do it during this week.
Thanks! 👍

**Comment by mmariuzzo** [comment]
Hi Sergio,

feel free to contact me for every needs.

Can I ask you if there are some rumors about new GA release time?


Il 27/02/2017 18:15, Sergio Gonzalez ha scritto:

**Comment by sergiogonzalez** [comment]
Hey @mmariuzzo I have no idea man, sorry :(

BTW, i sent me a pull request with your changes + my changes to run all the tests in the CI
https://github.com/sergiogonzalez/liferay-portal/pull/3847

I didn't do `ant all` so the pull might not even compile, but I'll check it when I have the results.

Feel free to take a look at my changes and we can discuss them. 

Everything in your pull looks good. The only thing that I have some concerns is regarding the new interface and util:  DocumentConverter and DocumentConverterUtil. It seems a duplicate of DocumentConversionUtil and it's an interface that it's in core and I'd like to avoid adding new interfaces to core as much as possible.

**Comment by mmariuzzo** [comment]
I've had the same concerns. To have a plugable conversion system the actual DocumentConversionUtil, imho, is not so friendly.

My first idea was to remove the actual DocumentConversionUtil from the core and implement a new, wider, API as a bundle. And migrate actual OpenOffice integration as an implementation.
In the core the actual is used by:
- PDFProcessorImpl.java, to convert documents to pdf
- WebServerServlet.java, to convert documents on the fly

But do that I have to touch more files, and answer this question: can this functionality be provided only as bundle?

I'm thinking about granting compatibility for plugin developed as separated war we cannot use as wab.

If you want I can start this refactor process and provide a new pull request only with this

**Comment by mmariuzzo** [comment]
About CI tests, maybe I've not modified the build.gradle in the right way?

**Comment by mmariuzzo** [comment]
HI Sergio, any news? Are yuo waiting something from me?

I'm working on DocumentConvertionUtil, and I hope to submit a new PR about it next week

**Comment by sergiogonzalez** [comment]
Hey @mmariuzzo 
Sorry this is taking longer than expected but we are in the middle of another development that is taking most of my time :(

Good news is that I have everything ready to merge (except the DocumentConvertionUtil) that we will leave for another pull. I didn't have time today to do some testing but I'll do it tomorrow and if everything looks good we should be ready to merge it. 

These are the changes so far that I was planning to send (considering that all the tests pass): https://github.com/mmariuzzo/liferay-portal/pull/1

Let me know if the code looks good to you or if there's anything you'd like to discuss.

I'll close this pull and we can continue the discussion in the pull I sent you: https://github.com/mmariuzzo/liferay-portal/pull/1

Thanks  @mmariuzzo

**Pull request closed without merging**
