### PR TITLE
LPS-75133

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @sergiogonzalez,

I added the test that you asked for. Let me know if you want the test to work differently. My understanding is that we're mainly just interested in making sure a SQLException doesn't get thrown when the upgrade process is run.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @mbowerman it seems that the tests failing are real. There seems to be a compilation issue.
Can you please check it and resend?
Thanks!

**Pull request closed without merging**
