### PR TITLE
[TECHNICAL-SUPPORT] LPS-70810

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann can you please check the tests? It seems that the test failures are real:

https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=8,label_exp=!master/24132/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/

```
junit.framework.AssertionFailedError: 
Unable to extract metadata
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:168)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:100)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:90)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:88)
```

**Comment by BryanEngler** [comment]
new pr at https://github.com/sergiogonzalez/liferay-portal/pull/3828

**Pull request closed without merging**
