### PR TITLE
LPS-80082 "Recent changes" of Wiki portlet is not sorting based upon recent changes and not updating the timestamp of last change

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

Thank you for fixing it. I was changing it right now.

I was going to change all my uses of getPageId for getResourcePrimKey in all the test in order to improve the consistency.

Regards!

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/64. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/9a82575~5...9a82575) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
