### PR TITLE
LPS-70229 Implementing the new interfaces in message boards

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hola Sergio,

Esta es la pull con los cambios en la api de upload. Los cambios están en los 7 últimos commits desde el último de tu anterior revisión. Lo de siempre: cualquier cosa, me dices.

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @4lejandrito 
I didn't have much time to review this pull so I just took a quick look. It looked good, but I found it weird that we have a DefaultUploadResponseHandler as an interface. Shouldn't we just have DefaultUploadResponseHandlerImpl that implements UploadResponseHandler and marked with some property or something to indicate that it's "special"? Maybe it should have a different name instead of Default?
@adolfopa could you review this one?

**Comment by 4lejandrito** [comment]
Forwarded to: https://github.com/adolfopa/liferay-portal/pull/506.

**Pull request closed without merging**
