### PR TITLE
[TECHNICAL-SUPPORT] LPS-69814

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-69814

Hello @sergiogonzalez ,

Here is the new PR for LPS-69814 based on the latest Master.

Reasoning for the fix is here: https://github.com/sergiogonzalez/liferay-portal/pull/4495

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @sergiogonzalez ,

Congratulations on the 7.1 release!

Test looks good for the PR here. Please take a look when you have time. Thanks.

Sincerely,
Brian Kim

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/1. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @brianikim pull looks good to me. I have sent the pull to @boton for further review. Thanks!

**Pull request closed without merging**
