### PR TITLE
LPS-85306 Use a more sensible default value for _maxFileSize

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz 

I'm sending the solution that you suggested in https://github.com/robertoDiaz/liferay-portal/pull/727#issuecomment-420669014

It is working fine.

Could you please test it too?

Thank you and best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @robertoDiaz @IstvanD
Since the taglib RepositoryEntryBrowser is not tight to Documents and Media I would rather have the max size value as it is and set the parameter taglib to whatever value is needed based on the case (journal might have different max size, blogs, etc). 
See this use case for example: https://github.com/liferay/liferay-portal/blob/master/modules/apps/blogs/blogs-item-selector-web/src/main/resources/META-INF/resources/blogs_attachments.jsp#L89
Thanks

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Thank you for the feedback.
I have already prepared a version of the solution that passes maxFileSize as a parameter to the taglib calls.
Should I send the pull reques to to you?

Thanks,
István

**Comment by robertoDiaz** [comment]
This is not deadly code at all.

This is used, for example in the WikiAttachmentCreoleEditorConfigContributor (see the uses of WikiAttachmentItemSelectorCriterion) and KBAttachmentEditorConfigContributor (see the uses of KBAttachmentItemSelectorCriterion)

> What do you think, should the maxFileSize passed to liferay-item-selector:repository-entry-browser in KB and Wiki anyway?

For example, in wiki I've found references to _dlValidator.getMaxAllowableSize() in the EditPageAttachmentsMVCActionCommand action.  Anyway I'm checking if this apps are using this method somehow to validate their attachments size.

I'll come with my conclusions ASAP

**Comment by robertoDiaz** [comment]
It seems that if we configure the DL service in setting to 1000 . (1 kb) we could upload bigger files in wiki. 

It means that the reference to _dlValidator.getMaxAllowableSize() is wrong (we should use the _uploadServletRequestConfigurationHelper.getMaxSize() in this case)

It seems that the attachments view is not working, so I'm not sure about this (but it's mostly probable that it works as wiki)

So, at the light of this, it seems that we do not have to add this attribute to wiki and kb (MB doesn't have an attachments selection view)

Thanks!!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

Is it OK then if I send the solution as in https://github.com/robertoDiaz/liferay-portal/pull/727 (setting `maxFileSize` only for DM and Journal) ?

Thanks,
István

**Comment by robertoDiaz** [comment]
yes, you could send ti.

Thanks for your patience, and sorry for the inconveniences

**Comment by IstvanD** [comment]
Sure.
I've send it to https://github.com/sergiogonzalez/liferay-portal/pull/4591

**Pull request closed without merging**
