### PR TITLE
Lps 73463

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hi @sergiogonzalez, this is been in review for over a month.  Can you take a look at it?

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary sorry about that, this pull got missed in my list and I didn't checked. 
I need to ping a few people from frontend about this, because I think that we cannot limit the scope of all those config contributors because some of them are **default behaviours** that should affect to every editor out there. However, there might be a few that we might limit so it's faster.

**Comment by sergiogonzalez** [comment]
I know that DocumentsAndMediaURLEditorConfigContributor.java and ImageEditorConfigContributor.java shouldn't be restricted to any particular scope because they are the default behaviour for every editor. 
I think that the exact thing applies to AudioEditorConfigContributor.java and VideoEditorConfigContributor.java but I think that @carloslancha can confirm it since he implemented those.
Keep in mind that all these ConfigContributors are in item-selector-editor-configuration and that's a module that is not specific to any application but the default behaviour that applies to every editor out there, so that's why we cannot limit the scope. 
If you see other ConfigContributor such as wiki: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-editor-configuration/src/main/java/com/liferay/wiki/editor/configuration/internal/WikiTextEditorConfigContributor.java or blogs: https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/blogs/blogs-editor-configuration/src/main/java/com/liferay/blogs/editor/configuration/internal/BlogsContentEditorConfigContributor.java or message boards https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/message-boards/message-boards-editor-configuration/src/main/java/com/liferay/message/boards/editor/configuration/internal/MBAttachmentHTMLEditorConfigContributor.java you will see that all of them are restricted because they belong to a particular app and use case.

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary I'm going to close the pull unless @carloslancha or @jbalsas want to modify the one regarding Audio or Video
Thanks!

**Comment by Preston-Crary** [comment]
Hi @sergiogonzalez,

I realize they are the defaults.  It just doesn't make sense to me that these are also used for titles, subtitles and comments when those do not allow these types of content anyway.

Anyway, we'll leave the final choice up to you.

**Comment by sergiogonzalez** [comment]
Hi @Preston-Crary 

Yeah, I understand what you mean, but unfortunatelly the configContributors scope doesn't support to say something like "apply everywhere except..." because that's exactly what we would need here.
If we implement that kind of scope selector we will apply in the default configuration to exclude the cases you mentioned.

Thanks

**Pull request closed without merging**
