### PR TITLE
LPS-53738

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Sergio,

I'm not sure why we're utilizing GetFileAction in the Recent Downloads portlet, but it makes more sense to simply get the URL and this also avoids strange forwarding issues. Let me know if you have any questions.

Thanks.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
