### PR TITLE
[TECHNICAL SUPPORT] LPS-73786 com.liferay.portal.upgrade.v7_0_0.UpgradeSocial upgrade process is not setting the Counter value high enough

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-73786

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:reopen

**Comment by NorbertKocsis** [comment]
Hi Sergio,

As this issue is DXP upgrade related it is very important for us on support right now. Could you please prioritize this?

Thanks,
Norbert

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/NorbertKocsis/liferay-portal/pull/45. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/abe9663~2...abe9663) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
