### PR TITLE
LPS-53444

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @kayleen-lim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Sergio,

I wasn't too sure about https://github.com/jonathanmccann/liferay-portal/commit/6462fa0386f477f71cbd5c43f42b0c34a24ef53f but I couldn't find another way to craft the URL without the themeDisplay.

Thanks.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann 

I still don't get why we need to modify this. What is the use case for this? To me it doesn't make much sense since we are generating a URL to the control panel (where users may not have access to) and I think that we are actually creating a mechanism for something that we already support in a different way.

There are different ways we can send the information regarding the URL: through the serviceContext attribute "entryURL", populating the layoutFullURL of the serviceContext, through the themeDisplay... so I don't fully understand why is that needed?

Thanks!

**Comment by kayleen-lim** [comment]
Hey @sergiogonzalez 
The workflow URL will be crafted in this way when the MBMessage is created through the JSONWS API. When this happens, the themeDisplay and layoutFullURL of serviceContext are null and the attribute "entryURL" of serviceContext is an empty string.

**Comment by sergiogonzalez** [comment]
Can't the caller set the attribute to the servicecontext? I don't think that creating a control panel url is a good solution for this case. 

Sergio

**Comment by kayleen-lim** [comment]
Hi Sergio,

I agree that creating a URL this way is not the best solution.
I am not sure what you mean by the caller.
There is also a possibility that a message boards portlet has not been
instantiated in the portal, in which case, would a control panel URL be
appropriate?
Thanks!

**Comment by sergiogonzalez** [comment]
What I mean is that the client invoking the json service should set the attributhe in the servicontext with the url for the notification. 

Otherwise I'd assume that we dont need to notify. 

So, I think that we shouldn't change the logic to support more cases for generating the url. We should either use one of the existing or assume that we won't send a notification. 

Sergio

**Comment by kayleen-lim** [comment]
Okay, thanks for the feedback, Sergio. I will find a way for the user to
set the entryURL attribute optionally.

**Pull request closed without merging**
