### PR TITLE
[Technical Support] LPS-60205 MediaWiki import logic

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Sergio,

we have some issues at Wiki page importing nowadays. The process can import MediaWiki format only, however, it converts that to Creole format all the time which may cause several problems.

I think, this conversion is there because that had been implemented before we started to support the MediaWiki format at all.

In addition, with this we could prevent several issues that would come because of the conversion and in this way all the advantages of the MediaWiki format that we would lose during the conversion can be kept after the import.

Because of these, I think, we could use simple import for MediaWiki in real MediaWiki format instead of converting if the default format setting allows that.

What do you think?

Thank you in advance,
Zsigmond

### CODE REVIEW

**Comment by zsigmondrab** [comment]
ci:retest

**Comment by zsigmondrab** [comment]
Hi Sergio,

as I can see the test failure is not because of our changes. Let me know if I am not right.

Thank you,
Zsigmond

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @zsigmondrab,

I'm going to ask @jorgeferrer opinion about this since he's the one who created this class and probably can give us more insight in this topic.

**Comment by JorgeFerrer** [comment]
Hey @zsigmondrab,

I'm not opposed to these changes, although I'm not a big fan of them for the following reasons:
1) Because they are improvements and we should be focusing on improving quality to launch Liferay 7 ASAP
2) Because I think it was a mistake to support MediaWiki. It's not a formally defined language. It's just whatever wikipedia does, and that's very very problematic. While we need to keep the support now, I would demote it to a plugin you need to install and maybe make it community supported.
3) Because most modern wikis seem to be taking a visual approach and leaving wiki syntaxes behind. We need to evaluate whether we want to go in the same direction. If so, I wouldn't want to invest much more on wiki syntaxes.

If after reading this you feel strongly about the need of this improvement, please send me the pull.

**Comment by zsigmondrab** [comment]
Forwarded to https://github.com/JorgeFerrer/liferay-portal/pull/598

Thank you,
Zsigmond

**Pull request closed without merging**
