### PR TITLE
LPS-53812

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey @sergiogonzalez 

Could you have a look at this pr? It is an issue from our customer. 

Thanks
John

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Yup! Looking at it right now...

There are 2 different LPS in this pull? Or is it a typo?

On Thu, Mar 5, 2015 at 3:12 PM, John Zhao <notifications@github.com> wrote:

> Hey @sergiogonzalez <https://github.com/sergiogonzalez>
>
> Could you have a look at this pr? It is an issue from our customer.
>
> Thanks
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergiogonzalez/liferay-portal/pull/2003#issuecomment-77369596>
> .
>



-- 
*Sergio González*
Core Engineer, Liferay España y Portugal.
Enterprise. Open Source. For Life.


Enterprise. Open Source. For Life.
Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es <http://twitter.com/liferay>

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Comment by zxdgoal** [comment]
Two LPS.

**Comment by zxdgoal** [comment]
53811 rename some methods. So I have to append 53812

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/zxdgoal/liferay-portal/pull/4. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
