### PR TITLE
LPS-85419 Put the subscriptionClassName in quotes

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
This pull changes the behaviour related to className so users that might be already subscribed to comments will see their subscriptions broken with this code because the classname no longer matches.
We need an upgrade in every module that is using comments with subscription to ensure that if there were users subscribed to the comment they will still be subscribed with this code. 
Ideally we should have some centralized logic piece that will facilitate/perform the upgrade and each of the affected modules can easily upgrade using it.
@robertoDiaz will take a look at this

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

I wrote a script that set the `classNameId` of the existing subscription to that of the new `className` `MBDiscussion.class.getName() + StringPool.UNDERLINE + className`.

The customer had the issue with JournalArticles, this I prepared them a groovy script like this:

```
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.service.ClassNameLocalServiceUtil;
import com.liferay.petra.string.StringPool;

String journalArticleClassName = com.liferay.journal.model.JournalArticle.class.getName();
String MBDiscussionClassName = com.liferay.message.boards.model.MBDiscussion.class.getName();
String subscriptionClassName = MBDiscussionClassName + StringPool.UNDERLINE + journalArticleClassName;

long journalArticleClassNameId = ClassNameLocalServiceUtil.getClassNameId(journalArticleClassName);
long subscriptionClassNameId = ClassNameLocalServiceUtil.getClassNameId(subscriptionClassName);

String updateQuery = "update subscription set classNameId = " + subscriptionClassNameId + " where classNameId = " + journalArticleClassNameId;

DB db = DBManagerUtil.getDB();

db.runSQL(updateQuery);
```

Could we add something similar to a validation process?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
Hey @IstvanD 

I'm handling this by creating an upgrade proccess that will change all the comments clients subscriptions classNames.

The code you are providing is not fine, since in this case we should ADD a new subscription, and keep the old one, since we do not know if this subscription was created as an article subscription or a article comment subscription. 

Since the current  behavior sends a notification for both cases, we could create a clone, based in this subscription, and set the new classNameId to it.

Something like this:

```
List<Subscription> subscriptions =
			subscriptionLocalService.getSubscriptions(getClassName());

		for (Subscription subscription : subscriptions) {
			subscriptionLocalService.addSubscription(
				subscription.getUserId(), subscription.getGroupId(),
				MBDiscussion.class.getName() + StringPool.UNDERLINE +
					getClassName(),
				subscription.getClassPK());
		}
```

As you can see I've used a new service method to get all the subscriptions based in the className, that currently is not in master, but you could use a dynamic query in the script.

Regards!

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Thank you for the information.

Is someone currently working on the solution?
If not, I'll start to implement it.

Best regards,
István

**Comment by robertoDiaz** [comment]
Yes, I'm working on that.

You could send a SHD to the customer.

Once you finish with it, you could pass the LPP to me and I'll move the fix to master.

Are you ok with this??

**Comment by IstvanD** [comment]
Hey @robertoDiaz 

Many thanks for dealing with it.
I have released the current fix as an SDH.

You mean the LPS or the LPP which is the customer ticket?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
The LPP. Since it depends on the LPS I could handle both.

Regards!

**Comment by IstvanD** [comment]
Sure. I'll assign the LPP to you.

Regards,
István

**Pull request closed without merging**
