### PR TITLE
LPS-72884

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
This fix is also related to the customer issue reported in https://issues.liferay.com/browse/LPS-72670

https://github.com/mhan810/liferay-portal/pull/1346

**Comment by BryanEngler** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50487. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/30b574a~2...30b574a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
