### PR TITLE
LPS-67752 - Message Boards portlet is sorting threads oldest to newest instead of newest to oldest

### PR DESCRIPTION
**Pull request by daviddotzhang**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by daledotshan** [comment]
Hey sergio,
Thanks for helping review this pull request. before we sent to you this pull request we struggled on the semantic version error and finally solve it after you told us to run gradlew baseline  and we are appreciative.

Could you take some time to look at this pull request? this issue open long time for customer.

Regards,
Dale

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/adolfopa/liferay-portal/pull/352. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @daledotshan I'm sending the pull to @adolfopa because I have lot of things on my plate and I'm afraid I won't be able to review this pull this week, so Adolfo will take care of it.
Thanks!

**Pull request closed without merging**
