### PR TITLE
LPS-66478 Allow editing pages even if the wiki engine is not deployed

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/40728. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
