### PR TITLE
LPS-70277 Don't use Non-breaking space in Wiki title

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @robertoDiaz @hudakl 

I need more information about this ticket because looking at the LPS description and the fix, I cannot figure out what is the issue:

1. Is the issue caused because FriendlyURLs cannot properly manage the non break space?
2. Is it related to the fact that we use AlloyEditor for titles in wiki?
3. Is it related to the way the wiki engine generate links to other wiki pages?
4. Is this something that could happen in any other app like Blogs?

Can you guys give me more information about the root cause of the issue?
Can you guys also create a unit/integration test to ensure that the issue exists and that this fixes it?

Thanks!

**Comment by hudakl** [comment]
Hi Sergio,

Sorry, for my delayed reply. 
The main problem is that users would add a link to a page, say, "[[Hello Page]]", which would point to "Hello+Page". However, if the space was NBSP, then the actual link of the page would be "Hello%C2%A0Page", leading to the Wiki not being able to find the page in question. Visiting the friendly URL with the (escaped) NBSP works correctly.

The issue doesn't seem to related to Alloy Editor. It can be reproduced if you copy-paste something from an .odt or google edoc (e.g. the .odt attached to the LPS). 

The issue occurs with wikis as the links are generated via the title and nbsp could be in the titles. However, links to other entries are not generated via the name of the asset, but via other methods. 

Please let me know if this answers your questions.

Thank you,
Laci

**Comment by sergiogonzalez** [comment]
Hey @hudakl 

OK, I understand the issue now and I think that the fix is good. However, I think that we need to add the same check in at least one more place: renaming pages. Otherwise, if a user changes the title of a wiki page and introduces a new title with a NBSP it will break. See https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/wiki/wiki-service/src/main/java/com/liferay/wiki/service/impl/WikiPageLocalServiceImpl.java#L1770

Can you also please see if there's any other place where the same logic might be needed?

Could you also please write some integration test to ensure that the new logic works in both cases (adding new pages and renaming wiki pages). We should do that in WikiPageLocalServiceTest.

Thanks!

cc/ @robertoDiaz @zsigmondrab

**Comment by hudakl** [comment]
Hi Sergio,

Thank you for your reply. I'm working on the handling the update too and the tests.
I'll resend the pull, once I'm finished with it.

Regards,
Laci

**Pull request closed without merging**
