### PR TITLE
LPS-76663 Message boards orders inccorectly

### PR DESCRIPTION
**Pull request by hudakl**
Per Roberto's request, I'm sending the previous pull rebased:
https://github.com/sergiogonzalez/liferay-portal/pull/4308

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @sergiogonzalez 

Since the files are been changed this week, and to avoid rebase this pull again, can you try to prioritize this??

Thanks in advance.

**Comment by robertoDiaz** [comment]
Hey @sergiogonzalez /cc @hudakl 

Any update on this??

**Comment by sergiogonzalez** [comment]
Hey guys, I didn't have time today to check this but I'll do it Monday. Sorry for the delay.

**Comment by sergiogonzalez** [comment]
Sent to https://github.com/hudakl/liferay-portal/pull/13

**Pull request closed without merging**
