### PR TITLE
LPS-55533 Update tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
@robertoDiaz will resend with changes to avoid having specific logic for desiredReturnTypes

**Comment by sergiogonzalez** [comment]
And changing the internalProperty

**Comment by robertoDiaz** [comment]
See https://github.com/sergiogonzalez/liferay-portal/pull/2231

**Pull request closed without merging**
