### PR TITLE
LPS-70043 Removing duplicate keys from config

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:start

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47400. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/a4e815a~1...a4e815a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
