### PR TITLE
LPS-83563 Ensure that Document Library Search considers sharing permissions

### PR DESCRIPTION
**Pull request by arboliveira**
Hi Sergio, thought you'd like to have a final look at how it turned out after all the changes we made. If it looks good to you :shipit: I can send it directly to BChan (with a warning not to backport.)

cc/ @BryanEngler

https://issues.liferay.com/browse/LPS-83563

### CODE REVIEW

**Comment by arboliveira** [comment]
ci:test:relevant

**Comment by arboliveira** [comment]
ci:reopen

**Comment by arboliveira** [comment]
@sergiogonzalez Can you check these 2 failing tests? I'm not sure if they were okay before and I botched the source code somehow when solving rebase conflicts... Thanks :)

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62641. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/04e96e9~7...04e96e9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
