### PR TITLE
LPS-73938

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @hhuijser @arthurchan35 

Thanks for sending this fix. 

I have some questions that I would like to discuss with our Product Manager regarding how permissions should work in specific message boards messages. I don't know if we should do inheritance check in the replies or if we should only check if the user has permission on the thread. 

I have always found very confusing to have permissions in specific messages and I think that we need to clarify the behaviour.

Right now our PM is on vacation, so we might need to wait until he's back. Is this an urgent issue for the customer? 

Thanks

**Comment by samuelkong** [comment]
@sergiogonzalez 
The ticket is a bit urgent. The customer's ticket was due Aug 16.

**Comment by adolfopa** [comment]
Sergio is on vacation. I've sent the pull to Brian. See https://github.com/brianchandotcom/liferay-portal/pull/51167

**Comment by adolfopa** [comment]
@hhuijser Can you close this PR? Thanks!

**Comment by hhuijser** [comment]
Closing as requested by @adolfopa

**Pull request closed without merging**
