### PR TITLE
[TECHNICAL-SUPPORT] LPS-79998

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @fortunatomaldonado @jonathanmccann we don't want to change the styling of the editor UIs for blogs and wiki. 
Then, we would like to fix this issue by ensuring that when a new image is added a new line is introduced right after it to ensure that the user can easily navigate to that line. In order to do that we might need to modify a few lines:

1. Ensure that we add a `<br>` element after the image in Adaptive Media in this line https://github.com/liferay/liferay-portal/blob/master/modules/apps/adaptive-media/adaptive-media-image-js-web/src/main/resources/META-INF/resources/ckeditor/plugins/adaptivemedia/plugin.js#L121
2. Same in ckeditor here https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/itemselector/plugin.js#L399
3. We also need to ensure that a new line is added when the user drags and drops an image from their desktop to the editor. I don't know if the changes above will be enough for that case or if we need to do some more changes in other files.

Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @sergiogonzalez ,
Thank you for the information and guidance on this. I was wondering, would it be acceptable to have the editor match the padding of the other editors such as Web Content? This way the style does not change but the user continues to have the ability to add text. Let me know what you think and thanks again!

**Comment by fortunatomaldonado** [comment]
Hello @sergiogonzalez ,
If you can provide any information/feedback on the comment above I would truly appreciate it. 
Thank you for your help!

**Comment by jbalsas** [comment]
Hey @fortunatomaldonado,

> 1. Do we want a new line to be created when the image is inserted between text? To me this isn't really something that bad but something I am curious about.

It shouldn't be hard to check wether we're inserting at the end of document or somewhere in between. I think avoiding the extra line when in between might be preferable, but always adding the extra line is simpler logic and doesn't sound as bad either. I'd go with the simplest route for now and adjust after user testing.

> 2. If the image is added by itself, the user will be able to add text after it with this fix, but the user will not be able to add text before it. Do we want to add a line break before and after the image is inserted? Will this be an issue that an image will be inserted in their own line when being added?

Adding a line break before is way more intrusive and less intuitive. When writing, things flow top-bottom, so I wouldn't expect that extra line on top. Workaround is also fairly simple in this case, so I wouldn't go with the line before the image.

Style adjustments aren't safe either. Small changes in the layout, device size, differences in the theme or different css might bring back the issue. Fixing the interaction inside the editor is a lot safer and easier to maintain in the future imho.

**Comment by fortunatomaldonado** [comment]
Hello @jbalsas,
Thank you so much for your response and all the information you have provided. I will go and make the necessary changes.
I truly appreciate the help!

**Pull request closed without merging**
