### PR TITLE
[TECHNICAL-SUPPORT] LPS-82571

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-82571
/cc @achaparro

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by achaparro** [comment]
Hey @sergiogonzalez,

I don't know if you are holding this because the upcoming release, if that is the case we should go ahead since the upgrade processes should be included in 7.1.

Thanks!

cc/@JosemariaMunoz

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/60988. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
