### PR TITLE
LPS-55685 Add better exception messages for Ratings

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @eric-chi @sergiogonzalez,

Can we slightly modify the last part of the exception to be:
>"... is not a valid score. _Score should_ be between 0 and 1"

rather than 
>"... is not a valid score. _Should_ be between 0 and 1".

It's a seemingly insignificant change, but I think BChan might like it better?

**Comment by sergiogonzalez** [comment]
Hey @dustinryerson 

Sure, can you please do the change and fwd it to Brian? I'm totally OK with the suggestion.

Thanks!

**Comment by dustinryerson** [comment]
Thank you, Sergio! @eric-chi can you take care of this when you get a chance and send the pull to Jonathan McCann? I'm out of the office for the next couple weeks so I won't have the chance. Thanks!

**Comment by eric-chi** [comment]
Sure thing guys!

**Pull request closed without merging**
