### PR TITLE
LPS-82009 Add Adaptive Media configuration for image previews

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz 

I discovered that image thumbnails are generated by Adaptive Media, while image previews are still created the old way.
Now, that AM deals with rotation of images with Exif orientation metadata, the thumbnails are displayed in the correct orientation. This is not the case with previews.
The Thumbnail AM configuration is added automatically whenever a new portal instance is created.

I thought about adding a similar default AM configuration for previews.
According to my tests, if the image the preview is generated for contains Exif orientation data, the newly added Preview AM configuration correctly rotates the image.

This solves the issue of [LPS-76893](https://issues.liferay.com/browse/LPS-76893), but I opened the separate LPS for this, as this is may solve more issues, for example when the preview is viewed in Documents and Media (the preview orientation is wrong there too).

I added the new code in **adaptive-media-document-library-thumbnails** module, but if you think that the additions should be added to new module, like **adaptive-media-document-library-previews**, please let me know.

Thank you if you review the changes!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Do you think we can go with this solution?

Please let me know if you need further help or explanation on the ideas.

Thank you!

Best regards,
István

**Comment by sergiogonzalez** [comment]
Hey @IstvanD the pull looks good, but we are not merging any non critical bug/issue in master until we are done with the release to avoid including regressions.
I'll get back to this as soon as we have the release jars built.
Thanks

**Comment by IstvanD** [comment]
Hi @sergiogonzalez 

I understand, and I'm looking forward for the further developments.

Best regards,
István

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Is there a date scheduled for building the release jars?

Thank you and best regards,
István

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61140. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/51e8f8d~1...51e8f8d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
