### PR TITLE
LPS-52734

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Sergio,

Sending this one to you as well since it looks like you implemented the localization of friendlyURLs (LPS-34850).
See https://issues.liferay.com/browse/LPP-14490 for some discussion regarding the fix.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3218. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey guys,

I'm sending this to Julio since he needs to make the call about how it should behave when the friendly url is empty.

thanks!

**Pull request closed without merging**
