### PR TITLE
LPS-67467 Create upgrade process

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
@adolfopa te cierro la pull porque se rompen algunos tests de integración relacionados con blogs que parece que son reales: 

com.liferay.blogs.service.test.BlogsEntryStatusTransitionTest.testScheduledByUpdateToApproved
com.liferay.blogs.lar.test.BlogsEntryStagedModelDataHandlerTest.testImportedCoverImage
com.liferay.blogs.lar.test.BlogsEntryStagedModelDataHandlerTest.testImportedSmallImage

https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/29822/

**Pull request closed without merging**
