### PR TITLE
LPS-78055

### PR DESCRIPTION
**Pull request by JaredDomio**
cc @jonathanmccann @ChrisKian @joshuacords

ticket: https://issues.liferay.com/browse/LPS-78055

Problem: After a user Confirms/ignores a request notification the notification does not disappear from the search container. Instead the notification's body is replaced with the message "Notification no longer applies, notification for invite members was deleted".

Solution: The cause of the problem was the search containers results being populated with all of the notifications that were designated as 'actionRequired'. This filter was too broad because this includes request notifications that the user already clicked on/archived. The solution was to make sure the search container results were populated with notifications that have 'actionRequired==true' and 'archived==false'. Archived set to false means the notification has not yet been read.

It is also necessary to force a page refresh to get the updated search container to display correctly. The redirect url in `usernotification.jspf `is set via `userNotificationFeedEntry.getLink()` and gets passed to the `NotificationPortlet.java`'s `actionResponse.sendRedirect`. The two classes that setActionable() true, which causes them to be viewed in the Request tab, are `ContactsCenterUserNotificationHandler` and `InviteMembersUserNotificatoinHandler`. 

Both of these set the getLink() to "" which causes the redirect to be "" for request notifications. It was necessary for the currentURL to be passed to the redirect, but other types of notifications implemented the getLink() method which returned a non null value. To retain the functionality of other notification types and to get the functionality I needed for request notifications I created a check to determine what to set the redirect to. 

I also submitted a form instead of a request because the request was not forcing a page refresh. In a previous pr I tried using location.reload() after setting the request in notification/view.jsp to force a page refresh. However, This created a condition where the action was being processed after the page reloaded instead of before. To ensure the page is refreshed after the action is processed I instead submitted the form and set the method to 'post'.

Please let me know If you have any questions or further suggestions

Thanks!

### CODE REVIEW

**Comment by JaredDomio** [comment]
ci:test

**Comment by sergiogonzalez** [comment]
Hey @JaredDomio 
I understand the first part of changing the results based on actionRequired and archived and I agree with the changes.

It's the second part the one I'm having troubles with. As far as I know the "Request" section in notifications was thought to work without refreshing and without sending the form, that's why we just had a io request and we have an empty link for the redirect, because we don't need to do any redirect.

What issues do you see if we just merged the changes I sent you in https://github.com/JaredDomio/liferay-portal/pull/1 ? Do you see any bug that might happen in that logic? Anything I'm missing?

Thanks

**Comment by JaredDomio** [comment]
Hey @sergiogonzalez 

Sorry I didn't completely clarify the issue in my previous message. The problem is without refreshing the page the count that is displayed next to "request list" is not updated and the empty search container message does not appear. I provided some screenshots that show this. 

(Before request is read)
image

(After request is read the request list count is not updated)
image

(After page refresh request list's count is updated and empty search container message is shown)
image

**Comment by JaredDomio** [comment]
Hi @sergiogonzalez 

Does the above comment better clarify what the issue is?

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57320. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/5444334~1...5444334) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Yeah, it does make sense.
I just sent it to Brian.
Thanks!

**Pull request closed without merging**
