### PR TITLE
LPS-79141 Wiki portlet does not open linked document

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

Could you please review this pull request?

Thank you in advance!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Is there a preferred place when the conversion logic should be placed?
I reckon that at the time `XhtmlTranslator.visit(LinkNode linkNode)` is executed, `linkNode` should already contain the converted, absolute link, shouldn't it?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
hey @IstvanD 

Do we have any solution for this??

What is the current status of this??

Thanks!!

**Comment by IstvanD** [comment]
hey @robertoDiaz 

I could not find the time for dealing with this yet but I'll attend to it shorty.

Best regards,
István

**Comment by robertoDiaz** [comment]
@IstvanD 

Thanks!!

**Pull request closed without merging**
