### PR TITLE
LPS-67872 Do not delete the latestExistingFileVersion if it is a PWC

### PR DESCRIPTION
**Pull request by matethurzo**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @ChrisKian can you elaborate a little bit more about why this changed is needed? I don't fully understand why we want to avoid deleting the PWC version but not any other.
Could we also add some integration test to cover this? I guess in FileEntryStagedModelDataHandlerTest.java ?
Thanks @ChrisKian !

**Comment by ChrisKian** [comment]
Hey @sergiogonzalez ,

  This PR is trying to resolve an issue where if we check-out or lock a DLFileEntry, then enable staging and attempt to publish, we get an InvalidFileVersionException due to attempting to delete a DLFileVersion with PWC as the version.

  In FileEntry StagedModelDataHandler.doImportStagedModel line 530 (of this PR), we are making sure only one version of the DLFileEntry is published to live.  However, in the scenario I described above, the version LR tried to delete is the PWC version.  Since this version should not be removed (and cannot, otherwise an InvalidFileVersionException is thrown), I believed the best way to resolve this issue was to not delete the DLFileVersion if it is a PWC.  This entry should remain to designate the locked status of the file.

  Unless the 1.0 and PWC DLFileVersions of the DLFileEntry should not both exist at once, I am not sure how to resolve this issue other than the solution I provided.  If my solution is acceptable, I will start creating tests and resubmit the PR.

Please let me know if my solution is correct, if you have any questions, or how I should approach this issue.  Thanks!

**Comment by sergiogonzalez** [comment]
Hey @ChrisKian 
Yeah, I understand it now and I think you're right.
Please go ahead and start with the tests and send me the pull when you're ready.
Thanks!

**Comment by ChrisKian** [comment]
Will do, thanks @sergiogonzalez!

**Pull request closed without merging**
