### PR TITLE
LPS-53812

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey guys,

I'm not sure if it's a good idea to change by reflection the value of a PropsValues that is a constant.

```java
public static final String POP_SERVER_SUBDOMAIN = PropsUtil.get(PropsKeys.POP_SERVER_SUBDOMAIN);
```

Maybe we should remove the final and directly modify the value without using reflection?

**Comment by zxdgoal** [comment]
Is it safe to remove the final ?

It looks like we have no choice if we do not want overwrite POP_SERVER_SUBDOMAIN in portal-ext when we test MBUtil.

**Comment by zxdgoal** [comment]
Resent https://github.com/sergiogonzalez/liferay-portal/pull/2018.

**Pull request closed without merging**
