### PR TITLE
LPS-61966 Add subscribe control to info panel

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34588. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/193. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
