### PR TITLE
LPS-71271

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@sergiogonzalez can you please give this one priority? It's an urgent customer related one.

**Comment by sergiogonzalez** [comment]
Reviewing it right now...

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47734. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/beb11d3~3...beb11d3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi @sergiogonzalez 

I notice you mis-set linkdata for dataLink in wiki-web and KB-web, https://github.com/sergiogonzalez/liferay-portal/blob/b014c421d5b417a70c29b30131dff6b676832fb7/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/common/article_attachments.jsp#L48
and
https://github.com/sergiogonzalez/liferay-portal/blob/b014c421d5b417a70c29b30131dff6b676832fb7/modules/apps/collaboration/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/view.jsp#L389

Could you please check this?

Regards,
Hai

**Comment by sergiogonzalez** [comment]
Hey @yuhai what do you mean when you say mis-set? I changed the attribute in the taglib to have a different name because otherwise it would lead to issues if both the div wrapper and the link would contain the same data. Then, I make the distinction by creating a new attribute. 

Is that what you meant?

Thx!

**Comment by yuhai** [comment]
Hi @sergiogonzalez ,

I might have explained unclearly. I mean you mistyped attribute name linkData. You wrote "datalink" in wiki-web and KB-web, it should be "linkData". 

https://github.com/sergiogonzalez/liferay-portal/blob/b014c421d5b417a70c29b30131dff6b676832fb7/modules/apps/foundation/frontend-taglib/frontend-taglib/src/main/resources/META-INF/liferay-frontend.tld#L289

Regards,
Hai

**Pull request closed without merging**
