### PR TITLE
LPS-59944

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @sergiogonzalez,

Attached is an update for http://issues.liferay.com/browse/LPS-59944.  There are some additional changes in blogs and site admin so we wanted to send this to you before sending it through.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, this worries me a little bit.

I know we recently introduced the regression that forces this update, but this means we've introduced a major breaking change that will break every other `search-container` out there. Rather than fixing all of our instances, we should figure out if this is worth it or if it can be better fixed keeping backwards compatibility.

This was caused by some work in progress regarding search containers (see https://github.com/jbalsas/liferay-portal/pull/245). 

@sergiogonzalez, could you hold on this PR or forward it to me to assert how big the issue is?

Thanks!

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/jbalsas/liferay-portal/pull/249. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey guys,

I have forwarded the pull to @jbalsas as he asked.

Thanks!

**Pull request closed without merging**
