### PR TITLE
[TECHNICAL-SUPPORT] LPS-80609

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @sergiogonzalez I think I have fixed the test failures. I apologize it took so long.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Unfortunately, I am not sure how to get a store with this test, @sergiogonzalez, would you have an idea of what I may need to change?

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59535. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/c4432a60~2...c4432a60) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @SamZiemer it seems that the store is not needed because it's not actually used by the tests. Same happens with other services that are null. 
I'm sending the pull to Brian to test everything: https://github.com/brianchandotcom/liferay-portal/pull/59535

**Pull request closed without merging**
