### PR TITLE
LPS-75240

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @mbowerman

>This fix does not break the [Golden rule](https://grow.liferay.com/people/DXP-+How+to+code+upgrade+process+and+backport+rules#section-DXP-+How+to+code+upgrade+process+and+backport+rules-Golden+rule) for coding upgrade processes because the Golden rule was already broken beforehand as we were querying specific columns of the UserNotificationEvent table directly. Furthermore, in my testing, the this fix improved the performance from  4636724 ms (77 minutes) to 227877 ms (4 minutes) for my test data, according to the output of the logging timer. With these numbers, I would argue that this fix qualifies for the [exception to the Golden rule](https://grow.liferay.com/people/DXP-+How+to+code+upgrade+process+and+backport+rules#section-DXP-+How+to+code+upgrade+process+and+backport+rules-Exception) anyway. 

>Granted, my test data didn't have any payloads with actionRequired set. I tried altering the test data so that about half the payloads had an actionRequired variable in them, and the method took 1758741 ms (29 minutes) to run. This is still noticeably better than the previous time taken of 77 minutes, although the difference isn't as stark. My guess though is that actionRequired variable isn't included in the payload most of the time though - it sounds like something that would only be used for Workflow notifications.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Please see https://github.com/sergiogonzalez/liferay-portal/pull/4037#issuecomment-336842893

**Comment by jonathanmccann** [comment]
@mbowerman Also, please look at the use of ```TRUE``` and ```concurrentAutoBatch``` since those won't work across all databases.

**Comment by mbowerman** [comment]
@jonathanmccann `TRUE` should be fine since it's going through `runSQL`, which uses the `SQLTransformer`. We use the same thing in other parts of our code:

https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v6_2_0/UpgradeGroup.java#L42
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/upgrade/JournalServiceUpgrade.java#L167
https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-service/src/main/java/com/liferay/knowledge/base/internal/upgrade/v1_3_4/UpgradeKBComment.java#L39

Are you sure `concurrentAutoBatch` doesn't work across all supported databases? I think I meant to do `autoBatch` instead of `concurrentAutoBatch`, but as far as I can tell, the only difference between the two is that `concurrentAutoBatch` takes in a `Connection` directly, whereas `autoBatch` gets the `Connection` from the `PreparedStatement`. And we use `autoBatch` everywhere in our code without checking the database first. And it looks to me like we also use `concurrentAutoBatch` in several places where we don't check the database first:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/upgrade/v1_0_0/UpgradeDynamicDataMapping.java#L933
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeAsset.java#L121
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_1/UpgradeDocumentLibrary.java#L134

**Comment by holatuwol** [comment]
@mbowerman: I was worried that `TRUE` doesn't work across all databases because I thought the SQLTransformer might be looking for `[$TRUE$]`, but if you've confirmed that `SQLTransformer` makes the proper substitutions on other databases, then I'm fine with it.

The idea of concurrent auto batch has resulted in SQL Server steps potentially a very long time for large transactions as the undo transaction log builds up (in some cases, the progress is so slow that it looks like it could take years just to finish a single stop), so I'm worried about even more of that code pattern going into core.

**Pull request closed without merging**
