### PR TITLE
LPS-64225 Revert all commits (from 506c9fbe80a00c2036770e5348b33fa3f79aaff3 to 0cfd17e9aceb0a4e9eece1cf8b0bc6cbe467263a) as build is broken.

### PR DESCRIPTION
**Pull request by mdelapenya**
@sergiogonzalez, could you please push this to upstream? We cannot build portal as the portal-kernel-2.1.0-SNAPSHOT has not been published yet cc/ @shuyangzhou @brianchandotcom @preston-crary

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by shuyangzhou** [comment]
@mdelapenya what is this about?

**Comment by mdelapenya** [comment]
`ant all` cannot complete because portal-kernel-2.1.0-SNAPSHOT is not published. We finally did not push it to upstream, as we preferred to publish to local maven repo

**Comment by shuyangzhou** [comment]
Part of the ant all is to install the current version of portal- kernel, portal- impl, etc into local maven repo. 

That should not be an issue. If it is CI would break too.

**Comment by mdelapenya** [comment]
The problem comes from here: https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/journal/journal-service/build.gradle#L11 and https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/bookmarks/bookmarks-service/build.gradle#L9

**Comment by mdelapenya** [comment]
everyone here has suffered it:

```
[exec] * What went wrong:
     [exec] A problem occurred configuring project ':apps:collaboration:bookmarks:bookmarks-service'.
     [exec] > Could not resolve all dependencies for configuration ':apps:collaboration:bookmarks:bookmarks-service:compile'.
     [exec]    > Could not find com.liferay.portal:com.liferay.portal.kernel:2.1.0-SNAPSHOT.
     [exec]      Searched in the following locations:
     [exec]          file:/Users/manuel/.m2/repository/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/maven-metadata.xml
     [exec]          file:/Users/manuel/.m2/repository/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/com.liferay.portal.kernel-2.1.0-SNAPSHOT.pom
     [exec]          file:/Users/manuel/.m2/repository/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/com.liferay.portal.kernel-2.1.0-SNAPSHOT.jar
     [exec]          http://cdn.repository.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/maven-metadata.xml
     [exec]          http://cdn.repository.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/com.liferay.portal.kernel-2.1.0-SNAPSHOT.pom
     [exec]          http://cdn.repository.liferay.com/nexus/content/groups/public/com/liferay/portal/com.liferay.portal.kernel/2.1.0-SNAPSHOT/com.liferay.portal.kernel-2.1.0-SNAPSHOT.jar
     [exec]      Required by:
     [exec]          com.liferay:bookmarks-service:1.0.0
```

**Comment by shuyangzhou** [comment]
That's not right. This should not happen, ant all should install the portal snapshots first before starting modules.

We do the default thing all the time to let certain module to use the latest version of portal jars.

Besides CI was not complaining.

Can you ping @Ithildir ? Something must be wrong in the build logic when runs locally, however I did not get that error.

**Comment by Preston-Crary** [comment]
@mdelapenya I had the same error this morning.  A workaround that worked for me was to run "ant install-portal-snapshot" in portal-kernel and then "ant all".

**Comment by Ithildir** [comment]
I'm working on a fix..

**Pull request closed without merging**
