### PR TITLE
LPS-73336 Remove unused field

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @yuhai

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1008. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
