### PR TITLE
LPS-66776 Using thumbnailator for image scaling

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

Could you (or the current DM reviewer) please check this pull request?

Using the default graphics2D method of image scaling produces sometimes poor quality images.
I searched for various alternative approaches, and found that the [thumbnailator](https://github.com/coobird/thumbnailator) image scaling library produces the best quality.

I'm no a big fan of using third party tools when solving issues, but in this case it proved to be solution.

Please see more details in the corresponding LPS.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 

It seems that https://issues.liferay.com/browse/LPS-66776 was created as a regression of either https://issues.liferay.com/browse/LPS-66364 or https://issues.liferay.com/browse/LPS-65218 or both. When I revert both changes, the quality of the small images is as way better (as it used to be).

Then, I don't think that using Thumbnailator is the proper fix for this bug. I checked the source code and it seems that the last commit is more than one year ago, so I don't know if it's still active.

Considering that the changes of both https://issues.liferay.com/browse/LPS-66364 and https://issues.liferay.com/browse/LPS-65218 where introduced by @Preston-Crary and reviewed by @shuyangzhou, it's better if you get in contact with them to see what would be the proper fix for this.

I tend to think that we should rollback the changes of the ticket that introduced the regression (LPS-65218 or LPS-66364) and fix it in a different way that doesn't create this regression.

Thanks!

**Comment by sergiogonzalez** [comment]
Hey @IstvanD did you have the opportunity to send the pull to @Preston-Crary and @shuyangzhou ? JIRA alerted that there was no activity on that ticket the last 14 days. Thx!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

I couldn't find the time yet to contact them, but I'll do that shortly.

I'm sorry for the delay.

**Comment by sergiogonzalez** [comment]
No problem @IstvanD I just wanted to make sure that this ticket didn't get lost :)

**Pull request closed without merging**
