### PR TITLE
[TECHNICAL-SUPPORT] LPS-78794

### PR DESCRIPTION
**Pull request by brianikim**
Hello @sergiogonzalez ,

I am resending LPS-78794 with the change you have requested in:
https://github.com/sergiogonzalez/liferay-portal/pull/4267

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:retest

**Comment by brianikim** [comment]
Hello @sergiogonzalez ,

If you can review this by end of Friday, it would be greatly appreciated as the customer is an EU customer who requires a fix by next Tuesday.

Sincerely,
Brian Kim

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/56475. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/9f8cd84~2...9f8cd84) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
