### PR TITLE
LPS-75853 | master

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LPS-75853

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
I reopened this because we want to see the full result first.

cc @jpince

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@sergiogonzalez can you please review? see https://issues.liferay.com/browse/LPS-75853 for details

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/53091. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
