### PR TITLE
LPS-53557

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Sergio,

I wasn't sure about the formatting/ordering of this code since it seems we do it differently in every JSP. Let me know if you have any questions.

Thanks.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann 

Can you double check if this also happens in Journal? I think that we have almost the exact same logic in both portlets...

Thanks!

**Comment by kayleen-lim** [comment]
Hi Sergio,
I've been able to confirm that the same logic occurs in the Journal portlet.

**Pull request closed without merging**
