### PR TITLE
LPS-76525 adding token

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test

**Comment by linolaoj** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/53785. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/84bebfb~30...84bebfb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @linolaoj no need to retest this. The code looks good.
Thanks!

**Pull request closed without merging**
