### PR TITLE
LPS-54011 [WARNING] not to merge

### PR DESCRIPTION
**Pull request by izaera**
/CC @robertoDiaz
@sergiogonzalez maybe we can delete the two previous commits implementing criteria serialization and leave the last one only.

### CODE REVIEW

**Comment by izaera** [comment]
/CC @robertoDiaz 
@sergiogonzalez maybe we can delete the two previous commits implementing criteria serialization and leave the last one only.

**Comment by izaera** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26152. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
