### PR TITLE
LPS-64112 URL of document points back to deactivated site

### PR DESCRIPTION
**Pull request by IstvanD**
Hey Sergio,

Could you please review this pull request?

Thank you in advance.

Have a great holiday!
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 
Can you explain with more details the reasoning of this fix? I don't fully get the purpose of the changes and why they are necessary.
Thanks!

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Sure, I'm sorry that I didn't included an explanation in the pull description.

In processPrincipalException() the redirect path will be set to "/portal/login", which, if it has no "p_l_id" parameter, will lead to the Liferay site by default.
This will cause the "This site is inactive" message being displayed if this site is deactivated.

What I did is that I determined the layout based on the groupId in the file's URL, and led the LoginAction to the layout where the file belongs.

Best regards,
István

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 
I talked to @juliocamarero and he told me that the default Liferay site cannot be deactivated. I tested in master and I couldn't do it, so I'm assuming that this is reproduceable in a version that contains a bug that allows to deactivate the site. 
Julio told me that he remembers seing that bug, so that's the bug that should be fixed (not allowing to deactivate the default liferay site)
I'll close this ticket then.
Thanks!

**Comment by sergiogonzalez** [comment]
Actually @IstvanD would you mind closing the LPS ticket and maybe add a comment explaining this situation in the ticket? Thx!

**Comment by IstvanD** [comment]
Hey @marcellustavares 

Thank you for the information.
Actually, I was able to deactivate the Liferay site on master, and reproduce the issue.
The function is still available at Site Settings > General in the Contol Panel, but instead of a checkbox (as on 6.2.), it can be turned on/off with a switch button.

However, if it is still a bug, and it shouldn't come to LPS-64112 in the fist place, I will close the LPS with these remarks.

**Comment by juliocamarero** [comment]
Hey @IstvanD 

we missed that place. We just sent the pull to Brian: https://github.com/brianchandotcom/liferay-portal/pull/38513

thanks!

**Pull request closed without merging**
