### PR TITLE
LPS-68589 Cache should be localized

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @sergiogonzalez 
Do you get a chance to review this pull request? we have a ee customer is waiting for this fix if you can treat this review as high priority would be appreciative. 

Thanks,
Dale

**Comment by robertoDiaz** [comment]
hey, @daledotshan 

the backport to 62xee, has been sent here the last week: https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2238

the backport to 70xee has some failing tests and i'm fixing them.

Thanks

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45449. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/4e9154c~1...4e9154c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
@daledotshan 

Here is the 7.0.x-ee pr: https://github.com/ZoltanTakacs/liferay-portal-ee/pull/2250

**Pull request closed without merging**
