### PR TITLE
LPS-43440 Clean up deleted folder contents from DBStore

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @sergiogonzalez 

As we discussed over e-mail I've created a fix and tested it. Please review my changes.

Regards,
Vilmos

### CODE REVIEW

**Comment by vilmospapp** [comment]
HI @sergiogonzalez 

Somehow I didn't manage to catch this before rebase although running format-source task.

Now it's fixed.

Sorry.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @vilmospapp 

I was reviewing the pull but it seems that either I'm missing something or something is missing in the pull:  who invokes the new method cleanUp(Folder)? I was searching for usages and it seems that nobody is invoking it so I don't know how this is triggered. 

Can you please check it?

Thanks!

**Comment by sergiogonzalez** [comment]
Could we also add some tests to make sure that the feature is working as expected and make sure that nobody breaks the feature?

Thanks Vilmos!

**Pull request closed without merging**
