### PR TITLE
LPS-68897 Conversion without Guest permission does not include images when the url contains &imageThumbnail=1

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hey @sergiogonzalez ,

This is a brief explanation of the PR by the author.

> Hey @robertoDiaz
> 
> Sure.
> The patterns are matching URLs that can point to images.
> Because ampersands (&) were not allowed, and URL query parameters are delimited by ampersands. the URLs could not have more than one query parameter.
> 
> Best regards,
> István

**Comment by sergiogonzalez** [comment]
Hey @robertoDiaz @IstvanD 
This kind of changes with the regex are usually kind of dangerous and prone to regression bugs. 
I would like to have some unit tests to ensure that the functionality is working under different scenarios, and looking at the source code it shouldn't be a hard thing to do because we don't have many dependencies on that class 
If it cannot be done with a unit test we could always do it with an integration test. We should provide an inputstream with a text containing the content and ensure that the returned inputstream contains the proper manipulated content.
Thanks guys

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/54884. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/09faaf1~3...09faaf1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
