### PR TITLE
LPS-70632 Wiki title and parentTitle could create infinite loop

### PR DESCRIPTION
**Pull request by topolik**
Hi @sergiogonzalez,

this is a security fix. It is possible to execute infinite loop by creating a cycle in wiki pages.

The tests are failing on semver, I created a new package for ModelListener. I'm not sure if you want to export it or not and if to create packageinfo file. I leave it to you if possible.

Other than that tests should be green.

Thanks!

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3853. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/e2beef1~1...e2beef1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
