### PR TITLE
[TECHNICAL-SUPPORT] LPS-65463

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann  and @BryanEngler
Shouldn't we include the same logic in the previous line?

```
				PreparedStatement ps2 =
					AutoBatchPreparedStatementUtil.autoBatch(
						connection.prepareStatement(
							"update DLFileEntry set fileName = ?, title = ? " +
								"where fileEntryId = ?"));
```

**Comment by BryanEngler** [comment]
hey @sergiogonzalez, DLFileEntry does not have a status column so i dont think we need to worry about it?

**Comment by BryanEngler** [comment]
also if we restore the file from the recycle bin, the DLFileEntry title and filename get set to the values that are in the DLFileVersion (DLFileEntryLocalServiceImpl#updateStatus). so the values we set on the "in trash" DLFileEntries in this upgrade process will get overwritten during the restore

**Comment by sergiogonzalez** [comment]
Got it. Thanks 👍

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40019. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
