### PR TITLE
LPS-67188 Expand only the branch with the selected article

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@IstvanD I've made the behaviour configurable, so that the user can choose how the navigation menu behaves. Could you please take a look to check it still satisfies the customer's needs? By incrementing the "max nesting level" parameter in the portlet configuration you should get the desired behaviour.

Thanks!

**Comment by adolfopa** [comment]
@IstvanD I've made the behaviour configurable, so that the user can choose how the navigation menu behaves. Could you please take a look to check it still satisfies the customer's needs? By incrementing the "max nesting level" parameter in the portlet configuration you should get the desired behaviour.

Thanks!

**Comment by sergiogonzalez** [comment]
@adolfopa I think everything is good. The only thing that I'm missing is the language key for `maximum-nesting-level`.

If we are planning to backport this feature we should contact the Knowledge Management team to let them know about this new configuration setting, the use case it covers and the implications that using a big value might have in terms of usability issues.

**Comment by adolfopa** [comment]
See https://github.com/IstvanD/liferay-portal/pull/22

**Pull request closed without merging**
