### PR TITLE
LPS-25766

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey guys @daviddotzhang @daledotshan @hhuijser 

I don't understand why we may want to delete this file (https://github.com/hhuijser/liferay-portal/commit/e731fa5566773678d18abe94d72f67308ba0b91e#diff-7214810480a4b28c8e175fb23142ad4aR373) since it seems that its the file of the document? So, if we delete that file, we would be deleting the actual file of the document so it cannot be download in the future? Am I wrong?

Can you please send a new pull explaining that or changing it if necessary?

Thanks guys!

**Comment by daviddotzhang** [comment]
@sergiogonzalez @daledotshan @hhuijser 

for the first part, we just rename the variable,

and the second part:

1:when we use Xuggler or Imagemagic, we will use the files in temp folders temporally , when we have generated the real files under "server/data", we need to delete files under "temp/liferay/document_xxxx".

2:we  need to delete the file in:
/xxx/master/server/tomcat7.0.62/temp/liferay/document_conversion,

since there are three temp folders:document_conversion,document_preview,document_thumbnail.
we have delete the last two one.

3: and the actual file of the documents is in the path, it is still there:
/xxx/master/server/data/document_library/
/xxx/master/server/data//document_thumbnail.

**Comment by hhuijser** [comment]
@sergiogonzalez 

Does David's explanation make sense?
If so, do you mind reopening this?

**Pull request closed without merging**
