### PR TITLE
LPS-81360 Make selector compatible with staging.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test

**Comment by crodriguezy** [comment]
ci:test

**Comment by crodriguezy** [comment]
Hi @sergiogonzalez , we wonder if you had the chance to review these changes, as a customer is waiting for us to receive the fix.

Thank you!

**Comment by sergiogonzalez** [comment]
Hey @crodriguezy @marianoalvarosaiz 
Sorry for the delay. I'll send this today.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59133. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/dd8f4c6~3...dd8f4c6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
