### PR TITLE
LPS-54300 Update taglibs

### PR DESCRIPTION
**Pull request by marcellustavares**
Hi @sergiogonzalez, could you please take a look at my changes that affect DL?

I'm trying to avoid using the serialized representation of the DDMStructure and trying to use DDMForm class instead.

Could you please send back to me if you think it's ok? This is still a WIP.

Thanks a lot!

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hey @sergiogonzalez, did you have a chance to look at this?

Thanks

**Comment by sergiogonzalez** [comment]
Hey @marcellustavares sorry about it. I was on vacation last week and I couldn't review it but I'll give you feedback today.

Thanks!

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/439. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
