### PR TITLE
LPS-79877 Remove unncessary code from DLServiceVerify

### PR DESCRIPTION
**Pull request by achaparro**
Hi @sergiogonzalez,

We are removing useless code from verifiers taking into account that the new version (7.1) only allows direct uprgades from 6.1. The removed processes were added here:
https://issues.liferay.com/browse/LPS-14314
https://issues.liferay.com/browse/LPS-25835
https://issues.liferay.com/browse/LPS-30519

Thanks!
cc/ @jonathanmccann

### CODE REVIEW

**Comment by achaparro** [comment]
ci.test

**Comment by achaparro** [comment]
ci:test

**Comment by achaparro** [comment]
ci:reopen

**Comment by achaparro** [comment]
errors not related

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57979. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/17cc61a~1...17cc61a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
