### PR TITLE
LPS-71408

### PR DESCRIPTION
**Pull request by mbowerman**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @mbowerman can you explain why is this line needed https://github.com/sergiogonzalez/liferay-portal/pull/3874/commits/64f7f0c050f46330c20b65b75f2e86614090c65f#diff-89cc1d4c6ffa57ce7b6b870f0e2bee82R278?

Other than that I think the pull is ready to go.

**Comment by mbowerman** [comment]
I just copied it from the testFindByNoAssets method in DLFileEntryFinderImpl: https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/integration/com/liferay/portlet/documentlibrary/service/persistence/DLFileEntryFinderTest.java#L1215

I wasn't sure what it's purpose was; I thought maybe it was just making sure that the deletion of the asset entry got committed to the database? It can probably be removed though.

**Comment by sergiogonzalez** [comment]
Can you test if it works without that line, and, if so, send it to Brian? Otherwise leave it as it is and send it as well. Thanks @mbowerman !

**Comment by mbowerman** [comment]
Thanks @sergiogonzalez! It seemed to work fine without that line, so I removed it and forwarded the pull request to https://github.com/brianchandotcom/liferay-portal/pull/47830.

**Pull request closed without merging**
