### PR TITLE
LPS-68339 Rename Article portlet repository

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by adolfopa** [comment]
@sergiogonzalez Do you know if a version of KB with the 2.0.0 schema was released? If negative, we could modify the previous step instead of creating a new one only for this.

**Comment by sergiogonzalez** [comment]
We should check that in the Liferay Marketplace to be sure. Just download the latest available KB for 6.2 from Liferay Marketplace and see the version number that it created in the Release table. 

Sergio

**Comment by adolfopa** [comment]
Latest version on MP used SchemaVersion 1.3.4, so it is safe to modify the upgrade for 2.0.0. I'll resend with these changes.

Thanks!

**Comment by adolfopa** [comment]
btw, @4lejandrito @sergiogonzalez could you please close this PR? Thanks!

**Pull request closed without merging**
