### PR TITLE
LPS-51337 Documents can be created in external repository from Asset Publisher

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

I added a little modification - setting showMountFolder to "true", since otherwise it will be "false" - and with this solution, it works.

The rest is the same as https://github.com/IstvanD/liferay-portal/pull/9

Best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Sent to @IstvanD with some changes: https://github.com/IstvanD/liferay-portal/pull/9

**Comment by sergiogonzalez** [comment]
Sorry about this. I closed the wrong pull.

**Comment by sergiogonzalez** [comment]
Your changes look good. Fwding to Brian.

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/23871. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
No prob.
Thanks Sergio.

**Pull request closed without merging**
