### PR TITLE
LPS-55860

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
I didn't modify that file so it seems to be stemming from another commit.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann 

Couple of things regarding this pull:

1. I think that we shouldn't include the limitation of the 5 attachments in the message boards. It's something that was imposed from the UI (because of a limitation when selecting multiple files) and we shouldn't impose that limitation in the backend (we may actually change that for 7.0 so we don't have any restriction in terms of number of message boards attachments. So I wouldn't throw the exception and don't create a test for that.

2. The API method of WikiPageService is slightly different, since in wiki it also includes a parameter in the API for the mime type. I'm totally OK with getting rid of that parameter, but we should do it in both places (deprecating the wiki service method). If you do that, can you also test that we are not including this regression back https://issues.liferay.com/browse/LPS-32347 (instead of testing it in documents and media we should test it when uploading attachments to both message boards and wiki)

Thanks!

**Pull request closed without merging**
