### PR TITLE
LPS-55728

### PR DESCRIPTION
**Pull request by holatuwol**
Original fix in https://issues.liferay.com/browse/LPS-53444 is missing parameters in the method signature. Re-adding the missing parameters.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26754. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
