### PR TITLE
LPS-58499 git-commit-plugins

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Rebased now.

**Comment by izaera** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30100. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
