### PR TITLE
LPS-66608

### PR DESCRIPTION
**Pull request by mikakoivisto**
Upgrade Tika, POI and PDFBox with dependencies

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @mikakoivisto it seems that there are some compilation issues with this pull and that's why the CI is failing. This is the log from the CI:

```
build-common-java.compile:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] Compiling 2828 source files to /opt/dev/projects/github/liferay-portal/portal-impl/classes
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/util/FileImpl.java:68: error: package org.apache.pdfbox.exceptions does not exist
    [javac] import org.apache.pdfbox.exceptions.CryptographyException;
    [javac]                                    ^
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/metadata/TikaRawMetadataProcessor.java:40: error: package org.apache.pdfbox.exceptions does not exist
    [javac] import org.apache.pdfbox.exceptions.CryptographyException;
    [javac]                                    ^
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/util/FileImpl.java:426: error: cannot find symbol
    [javac] 			if ((throwable instanceof CryptographyException) ||
    [javac] 			                          ^
    [javac]   symbol:   class CryptographyException
    [javac]   location: class FileImpl
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portal/metadata/TikaRawMetadataProcessor.java:83: error: cannot find symbol
    [javac] 			if ((throwable instanceof CryptographyException) ||
    [javac] 			                          ^
    [javac]   symbol:   class CryptographyException
    [javac]   location: class TikaRawMetadataProcessor
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/util/LiferayPDFBoxConverter.java:60: error: cannot find symbol
    [javac] 			List<PDPage> pdPages = pdDocumentCatalog.getAllPages();
    [javac] 			                                        ^
    [javac]   symbol:   method getAllPages()
    [javac]   location: variable pdDocumentCatalog of type PDDocumentCatalog
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/util/LiferayPDFBoxConverter.java:83: error: cannot find symbol
    [javac] 		RenderedImage renderedImage = pdPage.convertToImage(
    [javac] 		                                    ^
    [javac]   symbol:   method convertToImage(int,int)
    [javac]   location: variable pdPage of type PDPage
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/util/PDFProcessorImpl.java:872: error: cannot find symbol
    [javac] 			List<PDPage> pdPages = pdDocumentCatalog.getAllPages();
    [javac] 			                                        ^
    [javac]   symbol:   method getAllPages()
    [javac]   location: variable pdDocumentCatalog of type PDDocumentCatalog
    [javac] /opt/dev/projects/github/liferay-portal/portal-impl/src/com/liferay/portlet/documentlibrary/util/PDFProcessorImpl.java:932: error: cannot find symbol
    [javac] 				pdDocument.openProtection(standardDecryptionMaterial);
    [javac] 				          ^
    [javac]   symbol:   method openProtection(StandardDecryptionMaterial)
    [javac]   location: variable pdDocument of type PDDocument
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 8 errors
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1382: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:410: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:140: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common-java.xml:52: Compile failed; see the compiler error output for details.
```

Can you please resend it?

Thanks!

**Comment by mikakoivisto** [comment]
Please look at the ticket!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/samanzanedo/liferay-portal/pull/7. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/a042ab0~6...a042ab0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
