### PR TITLE
LPS-63377

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @sergiogonzalez,

Attached is an update for http://issues.liferay.com/browse/LPS-63377.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @jonmak08 

I was reviewing the pull and although it may fix this particular issue for Message Boards I think that we need to think this solution with a wider scope, because this is something that to my understanding can happen everywhere in portal.

For example, what is preventing autofill to autofill the permissions? Because in every form in the portal, permissions is under a panel that is usually collapsed, so the users might not see that it has been autofilled and he would have this exact same issue.

And not only with permissions, but potentially with any other form in portal. Most of our forms contains at least one fieldset that is collapsed, so it could be autofilled and the user wouldn't notice. 

Therefore, I don't think that we should add this logic to Message Boards for now. I think it would be better to start a new conversation maybe with @natecavanaugh and @jbalsas to see how we should proceed with this bugs?

Thanks @jonmak08

**Comment by jonmak08** [comment]
Hey @sergiogonzalez,

I agree that this could happen elsewhere in portal and other forms, especially when there are fieldsets that are collapsible.  The big key here is the autofill is actually a browser thing trying to "smartly" fill in fields for the user if they desire.  There is no way to disable the browser autofill as far as I know, except for disabling the fields which not send the field data on form submissions.

As for why this was not autofilling in for permissions, the auto fill aspect will only fill in text fields with a specific name (password, first name, last name, address, zip, etc)  I do not think it will autofill any other type of input fields (checkboxes, radio fields, etc).

I am in favor of changing this globally, where we enable all children fields when ```toggleDisabled``` is enabled, but since we are close to the release, I figured we should tackle this on a case by case basis.  Making a global change like that might be better after the release.

@natecavanaugh and @jbalsas, what do you think? Do you think updating ```toggleDisabled``` would be a good idea?  Do you have any suggestions as to how we could "disable" the browser's autofill?

Please let me know if you have any questions. Thanks!

**Comment by jbalsas** [comment]
Hey guys, I think this grants a deeper discussion, and maybe the issue is not so critical as to rush a fix in at this point.

For one, I'm very concerned whenever we start talking about ways to circumvent what browsers do. I think we need to gain a deep understanding into how autofill works. Then, we can come up with a proper form-design-guidelines that could both, play nice with browser form features and harness their power when possible. Otherwise, looks like we keep monkey patching things and going against the world :(

**Comment by natecavanaugh** [comment]
Hey guys,
Sorry for the delay. I overall agree with Chema and Sergio that I don't think we should be handling this in this way.
For instance, just because the form fields are visually hidden doesn't mean they should be disabled. A screen reader won't necessarily see it as hidden, and shouldn't see the fields as disabled (if they'll show up at all).
(BTW, if you just put the disabled attr on the fieldset, it will disable all of it's children).


Though @jbalsas regarding monkey patching browser behavior, this one is something we've had to do a lot of testing and research into (we've fixed [the equivalent bug in My Account quite a few times now](https://github.com/liferay/liferay-portal/blob/5e115ce7db0a50c9b659d2c2e6db5a7eb598f663/modules/apps/foundation/users-admin/users-admin-web/src/main/resources/META-INF/resources/user/password.jsp#L85-L90) which I know you've looked at before as well).

I recently found [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164) which is addressing it, and it turns out that they've introduce a mechanism in the spec that will address this.

The gist is that we just need to use the `autocomplete` attribute to provide semantic information about the field.

So for each of these fields, we could do something like `<aui:input autocomplete="outgoing-user-name" label="user-name" name="outUserName" />`, and the field won't be completed.

You can see an [example here](http://codepen.io/natecavanaugh/pen/WwLaRw) (first you'll need to add a username/password, submit once, then reload the frame by doing `Command + Shift + 5`).

There is one caveat, which is that this doesn't work with Firefox, but since it's in the WHATWG spec now, I think it's only a matter of time before the other browsers pick it up.

What do you guys think?

**Comment by jbalsas** [comment]
Hey @natecavanaugh, I looked at the autofill feature before. That was exactly what I meant by being against `monkey patching`. We need to research how standard things are meant to work and stick to that as much as possible. We also need to train our app developers to use and understand those features, so our forms become more useful and secure ootb, and not by mere trial and error.

**Pull request closed without merging**
