### PR TITLE
[Technical Support] LPS-65190

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @BryanEngler @ChrisKian

https://issues.liferay.com/browse/LPS-65190

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by dustinryerson** [comment]
ci:retest

**Comment by ChrisKian** [comment]
I think these errors are unrelated.  They seem to deal with the DB, but my commits are minor JSP changes which only deal with rendering HTML.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39068. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
