### PR TITLE
[TECHNICAL-SUPPORT] LPS-72290

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @SpencerWoo:

>Changes
The first commit we use <aui:validator> to reject empty polls before submission.
>
>The second commit we increase the button size for consistency across other submit buttons (login, DDLs, Web Content -> Polls, etc) as well as to mitigate the issue of LPS-72383.
>
>Additional Notes
The behavior of polls matches the behavior of DDL -> Data Definition -> required radio buttons.
This frontend validation should prevent backend NoSuchChoiceExceptions.

### CODE REVIEW

**Comment by SpencerWoo** [comment]
Hi @sergiogonzalez ,
This is low priority but just checking in -- any updates on this?

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/marcellustavares/liferay-portal/pull/1876. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey guys, 
I was on paternity leave and I just came back today. Sorry for the delay.
This pull relates to Polls and it's lead by the Workflow & Forms team so I'm forwarding the pull to @marcellustavares
Thanks!

**Comment by marcellustavares** [comment]
hey guys, just fyi I'm not directly reviewing pull requests from polls or forms, any pull request related to these components can be sent to @leoadb, so he can distribute to the team.

Thanks

**Pull request closed without merging**
