### PR TITLE
LPS-69364 - Collaboration & DM Standardize HTML markup in Info Panel

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-69364

### CODE REVIEW

**Comment by kenjiheigel** [comment]
These tests passed in a previous pull. Going to reopen and retest.

**Comment by kenjiheigel** [comment]
ci:reopen

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by pat270** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45441. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/06d6356~1...06d6356) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
