### PR TITLE
LPS-51337 Documents can be created in external repository from Asset Publisher

### PR DESCRIPTION
**Pull request by IstvanD**
Hi Sergio,

Could you please review this pull?

Thanks a lot.

Best regards,
István

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @IstvanD 

I cannot merge this because it sets a new dependency with Asset Publisher and we are in the process of modularizing it, so sooner that later we won't have Asset Publisher in core so we cannot have this dependency here.

Then, instead of just using Portletkeys.ASSET_PUBLISHER I'd rather use a parameter in the request to decide whether we want to includeMountFolders or not. I don't know if we may use init-parameter for that?

Sergio

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Thanks for the review.
Probably we could use an init-parameter, but where should it be defined?
As I see, the Asset Publisher portlet has no portlet.xml document.

István

**Comment by sergiogonzalez** [comment]
portlet-custom.xml should do it.

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Thanks.
I initially thought it would identify the Asset Publisher portlet by the init-param template-path, which I would extract from the portletContext, however, I saw that in edit_file_entry.jsp, the value of this init-param is /html/portlet/document_library/.

**Comment by IstvanD** [comment]
Hey @sergiogonzalez 

Basically the information which this solution is using is from which portlet we navigated to Document Library portlet's edit_file_entry.jsp.

Is there an existing pattern in trunk how we extract this information using modules?

I didn't find one yet.

**Comment by sergiogonzalez** [comment]
Hey Istvan,

I think there are different options:

1. Instead of notifying which portlet is navigating to the document
library, we just send a parameter in the request with the desired action
(showToolbar, showTitle, ...) and we use that parameter to define the
behaviour.
2. However, as this seems to be the behaviour for the whole portlet and not
at a request level (when in some requests you want some behaviours and in
other requests a different one), I was thinking that maybe we could use
some portlet-preferences in portlet-custom.xml that we could read to decide
the behavior.

I think those 2 are the "nicest" solutions we can implement here, but maybe
you guys can come up with better ideas?

On Tue, Feb 3, 2015 at 4:13 PM, István András Dézsi <
notifications@github.com> wrote:

> Hey @sergiogonzalez <https://github.com/sergiogonzalez>
>
> Basically the information which this solution is using is from which
> portlet we navigated to Document Library portlet's edit_file_entry.jsp.
>
> Is there an existing pattern in trunk how we extract this information
> using modules?
>
> I didn't find one yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sergiogonzalez/liferay-portal/pull/1930#issuecomment-72667144>
> .
>



-- 
*Sergio González*
Core Engineer, Liferay España y Portugal.
Enterprise. Open Source. For Life.


Enterprise. Open Source. For Life.
Visit Us: www.liferay.com  |  Like Us: facebook.com/liferay  |  Follow Us:
twitter.com/liferay_es <http://twitter.com/liferay>

*Aviso de Confidencialidad: *Este mensaje de correo electrónico, incluidos
los archivos adjuntos, enviados en nombre de Liferay SL es para el uso
exclusivo del destinatario (s) previsto y puede contener información
confidencial y privilegiada. Se prohíbe cualquier revisión no autorizada,
uso, copia, divulgación o distribución. Si usted no es el destinatario, por
favor póngase en contacto con el remitente por correo electrónico de
respuesta y destruir todas las copias del mensaje original. Gracias.

*Confidentiality Notice: *This e-mail message, including any attachments,
sent on behalf of Liferay SL is for the sole use of the intended
recipient(s) and may contain confidential and privileged information. Any
unauthorized review, use, copying, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply e-mail and destroy all copies of the original message. Thank
you.

**Pull request closed without merging**
