### PR TITLE
LPS-69125

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @sergiogonzalez,

Attached is an update for http://issues.liferay.com/browse/LPS-69125.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Reseting since it threw that SEMVER error.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/pat270/liferay-portal/pull/188. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/4ac0b16~1...4ac0b16) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
