### PR TITLE
LPS-68580

### PR DESCRIPTION
**Pull request by sherlyliu**

### CODE REVIEW

**Comment by sherlyliu** [comment]
Hi @sergiogonzalez , I tested, it works fine.

**Comment by sherlyliu** [comment]
LPP ticket: https://issues.liferay.com/browse/LPP-22811

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44265. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/1fe0d20~6...1fe0d20) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Thanks @sherlyliu

**Pull request closed without merging**
