### PR TITLE
LPS-78183 When file entry gets the version do not perform the permission checks when you get the contentStream

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @sergiogonzalez 

Could you please check this pull request?
It is forwarded from https://github.com/IstvanD/liferay-portal/pull/60

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Reopening the pull request as test failures are not related to the solution.

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57548. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/82c0d05~1...82c0d05) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
