### PR TITLE
[TECHNICAL-SUPPORT] LPS-68309

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
The failing source formatting is not in the files changed by this pull.

**Comment by Alec-Shay** [comment]
Hey @sergiogonzalez, just want to chime in to point out we have an LPP waiting for this. See: https://issues.liferay.com/browse/LPP-22648

Could this get looked at soon? Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/Alec-Shay/liferay-portal/pull/2. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/17c383d~1...17c383d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @Alec-Shay 

I have sent you the pull with my changes here https://github.com/Alec-Shay/liferay-portal/pull/2
I removed the folder description appearing in the title because that wasn't the behaviour in 6.2 as far as I checked.  I left the description of the image when displayed in slideshow.

If it looks good to you, please forward the pull to Brian Chan. Otherwise, please send me another pull with your changes.

Thanks!

**Comment by ChrisKian** [comment]
Looks good.  Forwarded to BChan: https://github.com/brianchandotcom/liferay-portal/pull/43613

**Pull request closed without merging**
