### PR TITLE
[TECHNICAL-SUPPORT] LPS-68562

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @sergiogonzalez,

I wasn't sure if you wanted to change all references from "completed" to "resolved" so I held off on that since it would cause a version increase. Let me know if you want that done though and I can take care of it to make it a bit more clear between the front and back end.

Thanks.

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann yeah, we can leave it as "Resolved".
Thanks for taking care of this :)

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/43886. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
