### PR TITLE
LPS-52494 Remove expensive and unneeded calls from journal

### PR DESCRIPTION
**Pull request by juliocamarero**
... and bookmarks?

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Hey @juliocamarero 
Bookmarks shouldn't be needed since it uses ResourceBlock.

**Comment by Preston-Crary** [comment]
Hey @sergiogonzalez 
I realized I missed one today in DLFolderAssetRenderer#getIconCssClass, let me know if you want me to resend.

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary 

Could you please resend adding the DLFolderAssetRenderer and JournalFolderAssetRenderer?

However, instead of just disabling this feature, could you add a portal.property to decide whether portal should check number of items to display one icon or other. By default it should still do the check and if it's becoming a bottleneck people can disable it from portal.properties.

Thanks Preston!

**Comment by Preston-Crary** [comment]
Resent https://github.com/liferay/liferay-portal/pull/662

**Pull request closed without merging**
