### PR TITLE
LPS-59592

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @sergiogonzalez 

You mentioned you were still doing stuff on wiki. I see some commits came in yesterday and I was doing another batch of autofixing stuff, so I thought I'd send you what I got... Let me know if you want me to resend later...

**Comment by sergiogonzalez** [comment]
Hey @hhuijser 

Perfect timing!. We finished moving the Wiki to MVC so we are ready to merge this.

Thanks!

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31471. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
