### PR TITLE
[TECHNICAL-SUPPORT] LPS-76498

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/jonathanmccann/liferay-portal/pull/1484. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/04fd200~2...04fd200) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
