### PR TITLE
LPS-71068 Related asset for all content types except document is not displayed in the Related asset portlet.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@sergiogonzalez 

This is the master PR, seems right to me since the same code is included in META-INF/resources/wiki/view.jsp:116, document_library/view_file_entry.jsp:84 and more, and I assume that the expected behaviour is that the Message related assets appear in the Related Assets Portlet

Thanks!!

**Comment by robertoDiaz** [comment]
@rimisaadouwork, 

Please see my SF, Thanks!!!

**Comment by rimisaadouwork** [comment]
Hi @robertoDiaz,

Thank you for your SF. But do I need to do something for this PR?

Thanks!

**Comment by robertoDiaz** [comment]
@rimisaadouwork 

Nope, it was just for your information

Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/47736. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/1bd3fc2~2...1bd3fc2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
