### PR TITLE
LPS-51213 Image Gallery images are not being selected upon editing a web content after upgrading from 6.0.12 to 6.2.10

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @sergiogonzalez, this is fixing a bug from the migration of the image gallery to the document library. Can you please a have a look? the changes related to journal looks good to me.

thank you!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hey @IstvanD,

I have just talked to @sergiogonzalez to not to push this to master before finishing the upgrade process I'm performing right now since I realized that 30% of the image gallery links weren't changed to document library links. I need more time to analyze it in order to know what it's happening but I will be on vacation next week so we will talk again in 10 days more or less.

Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/achaparro/liferay-portal/pull/11. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by achaparro** [comment]
Hi @IstvanD,

After talking to @sergiogonzalez and @juliocamarero we have finally decided to avoid the modification of the verify process since they require a lighterweight solution.

Here is the proposal:
https://github.com/marcellustavares/liferay-portal/pull/565

Thanks!

**Comment by IstvanD** [comment]
Hi @achaparro 

Thank you for the information.

Cheers,
István

**Pull request closed without merging**
