### PR TITLE
LPS-83502 Add KBArticle to AntiSamy whitelist

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/63699. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/aa6b843~5...aa6b843) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
cc/ @topolik @csierra we might need to revisit some of the rules of antisamy because I think they are too strict and its forcing us to disable it in most of our apps :(

**Comment by topolik** [comment]
Hi Sergio,

the problem was with the link in the test or some other things?

**Comment by sergiogonzalez** [comment]
As far as the ticket says it's just the link

**Comment by topolik** [comment]
Please see https://github.com/sergiogonzalez/liferay-portal/pull/4623. Thanks

**Pull request closed without merging**
