### PR TITLE
LPS-46553

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
According to what we have discussed, we need to:

1. Simplify logic (specially the while-for-while loop) and create unit tests to cover the functionality.

Thanks!

**Comment by jorgediaz-lr** [comment]
I have simplified a bit the logic, see https://github.com/sergiogonzalez/liferay-portal/pull/2303

**Pull request closed without merging**
