### PR TITLE
LPS-84043: SF

### PR DESCRIPTION
**Pull request by renatodepaiva**

### CODE REVIEW

**Comment by renatodepaiva** [comment]
Hello @sergiogonzalez ! Since the master version was much different than the one I used on last commit, I created a new branch, cherry-picked the previous commits and included the modifications you suggested from https://github.com/sergiogonzalez/liferay-portal/pull/4550.

I also ran some preliminary tests here: https://github.com/renatodepaiva/liferay-portal/pull/19.

Thanks!

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by renatodepaiva** [comment]
Hello @sergiogonzalez, can you please run the tests again? I don't think that the errors we got are related to any of the committed changes.

Thanks!

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by adolfopa** [comment]
Hey @renatodepaiva,

I've sent you a PR with an alternative solution. See https://github.com/renatodepaiva/liferay-portal/pull/20

**Pull request closed without merging**
