### PR TITLE
LanguageImpl Javadoc

### PR DESCRIPTION
**Pull request by codyhoag**
Hi Sergio,

Once you've reviewed the Javadoc, send me a pull request with any edits/additions you've made. Thanks!

https://issues.liferay.com/browse/LRDOCS-1320

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/872. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @codyhoag 

I sent the pull to @shuyangzhou because he was involved in the design of the LanguageImpl class and it seems that there are some APIs that are kind of confusing and we may think about deprecating those in favor of other more consistent.

This is the pull https://github.com/shuyangzhou/liferay-portal/pull/872

Sergio

**Comment by codyhoag** [comment]
Thanks for the update, Sergio!

**Pull request closed without merging**
