### PR TITLE
[TECHNICAL-SUPPORT] LPS-74784

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Hey @mbowerman @jonathanmccann 

I think that we might be able to remove the upgrade you guys are trying to remove, but in this pull I think that we are changing the behaviour compared to what we have when both upgrades where running. 

Lines 67, 69 and 76 of https://github.com/sergiogonzalez/liferay-portal/pull/4007/commits/58c64781a77775541a8627ac36f6c303583a2d89#diff-924a5cdb959e9212f28c3ac799e3dae8L67 are not executed in the subsequent upgrade, so they are not duplicated.

With the code in this pull, we would have some UserNotificationEvent whose deliveryType might be 0, delivered might be false, and the jsonObject might still have the actionRequired in it. 
I think that we might need to move those lines to the subsequent upgrade to ensure that they are executed. 

Can you please verify this and make sure that there is not any other thing that we might be forgetting or not executing?

I'm ccing @robertoDiaz because he wrote that upgrade and he might be able to help you guys with this.

Thanks
Sergio

**Comment by mbowerman** [comment]
Hey @sergiogonzalez,

I noticed the things that you mentioned, but I simply interpreted them as bugfixes to the upgrade process rather than differences that require both upgrade processes to be run.

Regarding the first difference you mentioned: In v2_0_0, we have
`userNotificationEvent.setDeliveryType(UserNotificationDeliveryConstants.TYPE_WEBSITE);`
but in v2_1_0 we have 
```
if (deliveryType == 0) {
	userNotificationEvent.setDeliveryType(
		UserNotificationDeliveryConstants.TYPE_WEBSITE);
}
```
The v2_1_0 version seems more correct to me. If we run v2_0_0 first then we risk overriding a deliveryType that was set to something else with TYPE_WEBSITE. Now, most likely (I haven't investigated this), the deliveryType column was added in v2_0_0 and that's why we're setting them all to TYPE_WEBSITE. But if this is the case, then having that if check should be harmless, since all the deliveryTypes should default to 0 anyway when the column is added.

Regarding the second difference you mentioned: I don't see a difference here, other than where `userNotificationEvent.setDelivered(true);` is getting called in the code. In v2_0_0, it gets called [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/notifications/notifications-web/src/main/java/com/liferay/notifications/web/internal/upgrade/v2_0_0/UpgradeUserNotificationEvent.java#L69), but in v2_1_0, it gets called [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/collaboration/notifications/notifications-web/src/main/java/com/liferay/notifications/web/internal/upgrade/v2_1_0/UpgradeUserNotificationEvent.java#L90). In both cases, we're updating that value to true for every single entry in the table. So I don't see any functional difference between the two upgrade processes here.

Regarding the third difference you mentioned: In v2_0_0, we have
`userNotificationEvent.setActionRequired(actionRequired);`
but in v2_1_0 we have 
```
if (!userNotificationEvent.isActionRequired()) {
	userNotificationEvent.setActionRequired(actionRequired);
}
```

Once again, I'm going to give a similar explanation for the first difference as to why I believe this is OK. Since "false" is the default boolean after a boolean column is added to the database, we are only updating those entries that have not been processed yet, which after skipping the upgrade process to 2.0 should be all the entries. It should not be possible to have the database in a state where there is an entry for which the actionRequired column is true, but the payload has "actionRequired=false". This is the only state that this logic would cause problems for, but it should not be possible for it to be in this state to begin with, so I do not think that there is a problem here.

@robertoDiaz, Can you please give your thoughts on this?

**Comment by sergiogonzalez** [comment]
Hey @mbowerman 

We have checked your code again and now, with your explanation, it makes sense. I don't see anything that is missing from the old upgrade compared to the new one, so I think that it's ok if we want to remove it.

As we were analysing the code we also came up with something that could be improved as well and we would like to get your feedback about it:
in upgrade v2.1.0, in the method updateUserNotificationEventActionRequired we are setting the actionRequired of UserNotificationEvent to whatever value it had in Notifications_UserNotificationEvent. In the case this value is false, it will be updated again by the method updateUserNotificationEvents. So we were thinking that maybe it's worthy to include a check in the method updateUserNotificationEventActionRequired right after fetching the actionRequired from the set:

```java
boolean actionRequired = rs.getBoolean("actionRequired");

if (!actionRequired) {
	continue;
}
```

If we want to improve the performance even more, we might use just one query instead of 2 using a join to fetch the actionRequired from Notifications_UserNotificationEvent in case the table exists. If we do this, we would only be doing one select and iterating only once instead of doing to select queries and iterating both.

Let me know if you want to work in any of those improvements and please send a pull to @robertoDiaz or if you think they're not worthy then please resend me this pull as it is.

Thanks!
Sergio

**Comment by mbowerman** [comment]
Hey @sergiogonzalez,

Yes, I was planning to send a separate pull to improve the performance of the `updateUserNotificationEventActionRequired` method. We can do the whole thing in either one or two queries, depending on whether or not isSupportsUpdateWithInnerJoin is true.

I believe something like the following would work:

```
if (isSupportsUpdateWithInnerJoin()) {
				runSQL("update UserNotificationEvent set UserNotificationEvent.actionRequired = Notifications_UserNotificationEvent.actionRequired inner join Notifications_UserNotificationEvent on UserNotificationEvent.userNotificationEventId = Notifications_UserNotificationEvent.userNotificationEventId");
			}
			else {
				runSQL("update UserNotificationEvent set actionRequired = FALSE where userNotificationEventId in (select userNotificationEventId from Notifications_UserNotificationEvent where actionRequired = FALSE)");
				runSQL("update UserNotificationEvent set actionRequired = TRUE where userNotificationEventId in (select userNotificationEventId from Notifications_UserNotificationEvent where actionRequired = TRUE)");
			}
```
And actually, if false is the default boolean (rather than null) when the column is created, then we would only need to do the second sql statement in the else block, regardless of whether or not isSupportsUpdatesWithInnerJoin is true.

I was planning to do these changes as part of a separate LPS, but I haven't gotten around to it since it is very time-consuming to test and my backlog is rather high at the moment. But if you think I should do these changes as part of this LPS, please let me know and I can resend the pull request with them. Thanks!

**Comment by sergiogonzalez** [comment]
Hey @mbowerman,
I guess it's up to you. We can merge this pull for now and leave the other thing for later. 
Thanks,
Sergio

**Comment by mbowerman** [comment]
Hi @sergiogonzalez,

I'd prefer to do it in a separate LPS, just to better document what bugs are being fixed by these commits.

**Comment by mbowerman** [comment]
Hey @sergiogonzalez,

Would you like me to forward this pull request to someone, or do you want to forward it to Brian Chan?

**Comment by mbowerman** [comment]
Hi @sergiogonzalez,

FYI, I have created [LPS-75133](https://issues.liferay.com/browse/LPS-75133) for the performance improvement to updateUserNotificationEventActionRequired

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52069. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
