### PR TITLE
[TECHNICAL-SUPPORT] LPS-71946

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman @SamZiemer @SpencerWoo

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
Irrelevant test failure, this is also happening on other pull requests (e.g. https://github.com/brianchandotcom/liferay-portal/pull/48399)

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/48590

**Pull request closed without merging**
