### PR TITLE
LPS-62517 Fix tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zxdgoal** [comment]
Thank you :+1:

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38561. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
