### PR TITLE
LPS-74618 Update functional tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
@sergiogonzalez, any update on this?

If you are out of time, could I send it to @adolfopa?

Thanks!

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51610. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
