### PR TITLE
LPS-66985 Use correct bounds

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@sergiogonzalez @sharonchoi, I have disabled the failing tests for now:
https://github.com/liferay/liferay-portal/commit/88917f0915e9c808bf1adfebc5745ce1ad692e5d. 

When this pull is ready to go in, you can turn the tests back on under LPS-66985. Thanks!

**Comment by sergiogonzalez** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/41298. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/29b00e2~1...29b00e2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
hey @kenjiheigel @sharonchoi @adolfopa I just submitted the pull to Brian https://github.com/brianchandotcom/liferay-portal/pull/41298

**Comment by sergiogonzalez** [comment]
Thanks!

**Pull request closed without merging**
