### PR TITLE
[TECHNICAL-SUPPORT] LPS-79021

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by brianikim** [comment]
ci:retest

**Comment by brianikim** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56601. [See changes here.](https://github.com/sergiogonzalez/liferay-portal/compare/4375a6a~3...4375a6a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
