### PR TITLE
LPS-59252

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Sergio,

I remember you helped review with a friendlyURL one before, so sending this to you.

Thanks,

**Comment by zxdgoal** [comment]
Hey Sergio

Currently, if the locale calculated from portalImpl does not match the original locale from requested layout, we go straight without redirection. That is not a big problem.

However, I18npath is a bit different. For example, if I input localhost:8080/fr/web/guest/home and French is not an available locale for site guest, I will get the site displayed in site default locale, say English, but the URL is still /fr/web/guest/home.

This is not that user-friendly and could confuse end users as locale from URL does not match the locale displayed to them.

The best solution would be redirect to users to localhost:8080/en/web/guest/home to avoid this inconsistency.

What are your opinions?

BTW, you cannot test this pr until fixing LPS-59345, for which I still struggle.

Thanks
John.

**Comment by zxdgoal** [comment]
Re-sent here: https://github.com/sergiogonzalez/liferay-portal/pull/2603 with sorting commits.

**Comment by sergiogonzalez** [comment]
https://github.com/juliocamarero/liferay-portal/pull/3708

**Pull request closed without merging**
