### PR TITLE
LPS-66542 / LPS-66543 Fix cover image rendering and entry lookup

### PR DESCRIPTION
**Pull request by adolfopa**
@sergiogonzalez  There are two different issues here. I've sent the together to avoid conflicts.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40729. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
